Repository fossasia/open-event-server, pull requests merged in 2019-10, with the labels that each got.

#6478 chore: Fix GitHub action for dredd tests
  .github/workflows/dredd.yml
Labels: fix

#6480 chore: Add dredd tests to Circle CI
  .circleci/config.yml
  .github/workflows/dredd.yml
  package.json
  yarn.lock
Labels: chore

#6484 fix: Use explicit dependencies
  requirements/common.txt
Labels: fix

#6487 fix: Use explicit dependencies (#6484)
  requirements/common.txt
Labels: fix

#6488 chore: Add .env in docker compose and ignore override
  .gitignore
  docker-compose.yml
Labels: chore

#6489 fix: Use pool pre ping option to avoid dropped connections
  config.py
Labels: fix

#6490 chore: Use Python 3.7 in docker
  Dockerfile
Labels: chore

#6492 chore: Change flask-rest-jsonapi to taggd and tested version
  .circleci/config.yml
  Dockerfile
  requirements/common.txt
Labels: chore

#6497 feat: Increase gunicorn workers and allow more config
  .gitignore
  scripts/container_start.sh
Labels: feature

#6499 fix: Add workaround for multiprocess engine forking
  app/__init__.py
  app/models/__init__.py
Labels: fix

#6502 chore: Remove debugging print statements from listener
  app/models/__init__.py
Labels: chore

#6506 chore: Remove populate and fix various dredd tests
  .gitignore
  app/factories/role.py
  docs/api/blueprint/custom_system_roles.apib
  docs/api/blueprint/panel_permissions.apib
  docs/api/blueprint/user/user_permissions.apib
  dredd.yml
  tests/all/integration/setup_database.py
  tests/all/integration/test_migrations.py
  tests/hook_main.py
Labels: chore

#6512 chore: Add generated folder to docker volume mount
  docker-compose.yml
Labels: chore

#6510 fix: Fix and test cron job for Invoice Due Marking
  app/api/helpers/scheduled_jobs.py
  tests/all/integration/api/helpers/test_scheduled_jobs.py
Labels: fix

#6521 chore(docs): Update docs for python 3.7
  docs/installation/local.md
Labels: docs

#6523 fix: ICal Attribute error & add integration test
  app/api/helpers/ICalExporter.py
  app/models/speaker.py
  tests/all/integration/api/helpers/test_icalexporter.py
Labels: fix

#6531 chore(docs): Add CircleCI Build Status Badge
  README.md
Labels: docs

#6533 feat: Rewrite working pentabarf with proper and throrough tests
  app/__init__.py
  app/api/helpers/pentabarfxml.py
  app/factories/microlocation.py
  app/factories/session.py
  app/factories/speaker.py
  app/models/__init__.py
  app/models/utils.py
  config.py
  tests/all/integration/api/helpers/test_pentabarfxml.py
Labels: feature

#6535 chore(docs): Update README.md for python 3.7
  README.md
  docs/installation/basic.md
  docs/installation/local.md
Labels: docs

#6532 feat: add manage-scripts to switch system modules value
  README.md
  manage.py
Labels: feature

#6524 feat: Add endpoint for server version
  app/__init__.py
  app/api/server_version.py
Labels: feature

#6540 chore: Release v1.7.0
  CHANGELOG.md
  README.md
  app/api/server_version.py
Labels: chore

#6541 chore: Release 1.7.0 to master
  .circleci/config.yml
  .gitignore
  .travis.yml
  CHANGELOG.md
  Dockerfile
  README.md
  app/__init__.py
  app/api/helpers/ICalExporter.py
  app/api/helpers/db.py
  app/api/helpers/payment.py
  app/api/helpers/pentabarfxml.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/storage.py
  app/api/helpers/third_party_auth.py
  app/api/helpers/ticketing.py
  app/api/helpers/utilities.py
  app/api/server_version.py
  app/factories/microlocation.py
  app/factories/role.py
  app/factories/session.py
  app/factories/speaker.py
  app/models/speaker.py
  app/models/ticket_holder.py
  app/models/utils.py
  config.py
  docker-compose.yml
  docs/api/blueprint/custom_system_roles.apib
  docs/api/blueprint/panel_permissions.apib
  docs/api/blueprint/user/user_permissions.apib
  docs/installation/basic.md
  docs/installation/local.md
  dredd.yml
  manage.py
  package.json
  requirements/common.txt
  requirements/dev.txt
  runtime.txt
  scripts/container_start.sh
  tests/all/integration/api/helpers/test_icalexporter.py
  tests/all/integration/api/helpers/test_pentabarfxml.py
  tests/all/integration/api/helpers/test_scheduled_jobs.py
  tests/all/integration/setup_database.py
  tests/all/integration/test_migrations.py
  tests/hook_main.py
  yarn.lock
Labels: chore

#6543 chore: Lock python version in docker to workaround pip
  Dockerfile
Labels: chore

#6536 fix: Change association table name to ticket_tagging
  app/models/ticket.py
  migrations/versions/rev-2019-10-18-15:36:50-9effd270a6ae_association_table_name_change.py
Labels: fix

#6546 chore(docs): Correct API docs for update order
  docs/api/blueprint/order/orders.apib
Labels: docs

#6557 fix: Pin elasticsearch-dsl to 7.0.0
  requirements/common.txt
Labels: fix

#6558 chore: Remove redundant setup methods
  tests/all/integration/api/helpers/test_auth.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/all/integration/api/helpers/test_db.py
  tests/all/integration/api/helpers/test_errors.py
  tests/all/integration/api/helpers/test_events.py
  tests/all/integration/api/helpers/test_exceptions.py
  tests/all/integration/api/helpers/test_export_helpers.py
  tests/all/integration/api/helpers/test_files.py
  tests/all/integration/api/helpers/test_filters.py
  tests/all/integration/api/helpers/test_jwt.py
  tests/all/integration/api/helpers/test_log.py
  tests/all/integration/api/helpers/test_order.py
  tests/all/integration/api/helpers/test_storage.py
  tests/all/integration/api/helpers/test_systemnotifications.py
  tests/all/integration/api/helpers/test_user.py
  tests/all/integration/api/helpers/test_xcal.py
  tests/all/integration/api/validation/test_access_codes.py
  tests/all/integration/api/validation/test_discount_codes.py
  tests/all/integration/api/validation/test_sessions.py
  tests/all/integration/api/validation/test_speakers_call.py
  tests/all/integration/api/validation/test_tickets.py
  tests/all/integration/test_migrations.py
Labels: chore
