Repository fossasia/open-event-server, pull requests merged in 2019-06, with the labels that each got.

#5979 docs: add omise fields in events and settings schema
  app/factories/setting.py
  docs/api/api_blueprint.apib
Labels: docs

#5934 feat: Add is_ticket_form_enabled field
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/0e80c49a6e28_.py
Labels: feature

#5984 fix: migration split heads are sequential now
  migrations/versions/0e80c49a6e28_.py
Labels: fix

#5952 feat: Made invoice similar to Eventbrite
  app/api/helpers/order.py
  app/templates/pdf/order_invoice.html
Labels: feature

#5987 fix: Pin arrow and other dependencies
  requirements/common.txt
Labels: dependencies, fix

#5924 fix: allows deleted users to signup with same email
  app/api/helpers/user.py
  app/api/users.py
  migrations/versions/6f7b6fad3f56_refactor_deleted_users_email.py
Labels: fix

#5990 chore: Correct typo in event end mail
  app/api/helpers/system_mails.py
Labels: chore

#5960 feat: Alipay source creation and charge payment
  app/__init__.py
  app/api/helpers/payment.py
  app/api/orders.py
  app/api/schema/events.py
  app/api/schema/settings.py
  app/models/event.py
  app/models/setting.py
  migrations/versions/76aed36b4888_.py
Labels: feature

#5995 feat: Added required fields and schemas for ngo events
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/c517c6be040d_.py
Labels: feature

#5997 fix: Correct 'days' attribute not found in expire tickets
  app/api/helpers/scheduled_jobs.py
Labels: fix

#6002 fix: minor typo and add omise to payment-mode schema
  app/api/schema/orders.py
  app/api/schema/settings.py
Labels: fix

#6000 fix: adds unique constraint on role_invite
  app/models/role_invite.py
  migrations/versions/89a5b836b406_.py
Labels: fix

#6015 feat: add role name to json object
  app/api/role_invites.py
Labels: feature

#6008 feat: restricts unverified user for buying free tickets
  app/api/attendees.py
Labels: feature

#6010 fix: Fix session proposal email link
  app/api/sessions.py
Labels: fix

#6017 fix: add unique constraint making country-currency combination
  app/api/schema/ticket_fees.py
  app/models/ticket_fee.py
  migrations/versions/a6e5abbcc205_.py
Labels: fix

#6032 feat: add show_stats_public field
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/09c86e38f5e7_.py
Labels: feature

#6046 fix: Suspicious content errors on celery
  app/__init__.py
Labels: fix

#6013 feat: Send different email on role invite for existing user
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/role_invites.py
  app/models/mail.py
Labels: feature

#6024 fix: Implemented organizer access for attendee tickets
  app/api/auth.py
Labels: fix

#6004 feat: Omise charge route and payment flow
  app/api/helpers/payment.py
  app/api/orders.py
  requirements/common.txt
Labels: feature

#6050 fix: Only admin should be allowed to create event discount codes
  app/api/discount_codes.py
Labels: fix

#6009 fix: Revert PR for adding required fields of ngo events
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/14e31b3a860b_.py
Labels: fix

#6041 feat: Add an admin-only endpoint for test mail
  app/__init__.py
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/settings.py
  app/models/mail.py
Labels: feature

#6044 feat: Addition of fields for reCAPTCHA
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/232b13d4e86a_.py
Labels: feature

#6056 feat: List popular event locations at /event-locations
  app/api/event_locations.py
Labels: feature

#6062 feat: Model & schema validations for donations
  app/api/schema/tickets.py
  app/models/ticket.py
  migrations/versions/43e8c59337ae_.py
Labels: feature

#6071 fix: Correct server default type in migration
  migrations/versions/43e8c59337ae_.py
Labels: fix

#6035 feat: implement threshold for resetting password
  app/__init__.py
  app/api/auth.py
  requirements/common.txt
Labels: feature

#6073 fix: Correct env type in tests and config
  app/factories/common.py
  config.py
  docs/api/api_blueprint.apib
Labels: fix

#6080 fix: Honor environment set from .env
  app/settings/__init__.py
  config.py
Labels: fix

#5981 feat: SMTP as a fallback function when Sendgrid quota exceeds limit
  app/api/helpers/mail.py
  app/api/helpers/tasks.py
Labels: feature

#6081 test: Shifted admin check function and added integration test
  app/api/auth.py
  app/api/helpers/auth.py
  tests/all/integration/api/helpers/test_auth.py
Labels: testing

#6092 chore: Use development server on heroku for development config
  scripts/heroku.sh
Labels: chore

#6096 fix: Pass user object to send_notif instead of email
  app/api/helpers/scheduled_jobs.py
Labels: fix

#5880 fix: add checks for discount value
  app/api/schema/discount_codes.py
  tests/all/integration/api/validation/test_discount_codes.py
  tests/all/unit/api/validation/test_discount_codes.py
Labels: fix

#6095 fix: Ticket downloads for multi-attendee orders
  app/api/auth.py
  app/api/helpers/order.py
  app/api/helpers/storage.py
  app/models/user.py
Labels: Priority: URGENT, fix

#6100 fix: Query for speakers properly for after event cron job
  app/api/helpers/scheduled_jobs.py
Labels: fix

#6079 fix: updates message on reset password if user isn't registered
  app/api/auth.py
Labels: fix

#6110 fix: resolve error on multi-attendee invoice downloads
  app/api/auth.py
Labels: Priority: URGENT, fix

#6070 feat: implement checks on session rating
  app/api/feedbacks.py
  app/api/schema/feedbacks.py
  app/factories/feedback.py
  docs/api/api_blueprint.apib
  tests/hook_main.py
Labels: feature

#6098 feat: Model/schema additions for admin billing info
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/b08a4ffff5dd_.py
Labels: feature

#6084 feat: modify cancel notif message and add required links
  app/api/helpers/notification.py
  app/api/helpers/system_notifications.py
Labels: feature

#6108 test:Add Integration tests for account delete functions
  tests/all/integration/api/helpers/test_user.py
Labels: testing
