Repository fossasia/open-event-server, pull requests merged in 2019-07, with the labels that each got.

#6083 fix: Move order_expiry_time into settings model
  app/api/helpers/order.py
  app/api/schema/events.py
  app/api/schema/settings.py
  app/factories/event.py
  app/factories/setting.py
  app/models/event.py
  app/models/setting.py
  docs/api/api_blueprint.apib
  migrations/versions/2c7ff9781032_.py
  tests/all/integration/api/helpers/test_order.py
Labels: fix

#6129 fix: Fixed migration error and downgrade function
  migrations/versions/2c7ff9781032_.py
Labels: fix

#6103 fix: User billing details for paying event invoice
  app/api/schema/users.py
  app/models/user.py
  migrations/versions/4279c2ac565b_.py
Labels: fix

#6042 feat: Adds event owner role to the system
  app/api/__init__.py
  app/api/admin_sales/organizer.py
  app/api/events.py
  app/api/full_text_search/events.py
  app/api/helpers/export_helpers.py
  app/api/helpers/import_helpers.py
  app/api/helpers/notification.py
  app/api/helpers/permission_manager.py
  app/api/helpers/permissions.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/system_mails.py
  app/api/helpers/system_notifications.py
  app/api/helpers/ticketing.py
  app/api/orders.py
  app/api/roles.py
  app/api/schema/events.py
  app/api/schema/role_invites.py
  app/api/schema/users.py
  app/api/sessions.py
  app/api/users.py
  app/factories/event.py
  app/models/event.py
  app/models/search/event.py
  app/models/user.py
  docs/api/api_blueprint.apib
  migrations/versions/b2aca7268345_.py
  populate_db.py
Labels: feature

#6063 fix: Get and delete event favourite using event_id
  app/api/user_favourite_events.py
  app/factories/user_favourite_events.py
  docs/api/api_blueprint.apib
  tests/hook_main.py
Labels: fix

#6133 fix: Fixed multiple tickets error & refactored order invoice logic
  app/api/helpers/order.py
  app/templates/pdf/order_invoice.html
Labels: fix

#6117 fix: Migration for changing gender type
  migrations/versions/43e8c59339af_.py
Labels: fix

#6131 fix: checks on session and role-invite api and owner role
  app/api/admin_statistics_api/users.py
  app/api/role_invites.py
  app/api/sessions.py
  migrations/versions/43e8c59337ag_.py
  populate_db.py
Labels: fix

#6135 feat: add event date to response of order for admin sales revenues (formerly fees)
  app/api/admin_sales/fees.py
Labels: feature

#6130 fix: Added factories & billing model additions
  app/api/schema/settings.py
  app/api/schema/users.py
  app/factories/setting.py
  app/models/setting.py
  app/models/user.py
  migrations/versions/4bdb4809f519_.py
Labels: fix

#6146 fix: Removed currency symbol filter
  app/templates/pdf/order_invoice.html
Labels: fix

#5927 fix: Make discount code case insensitive
  migrations/versions/ba651e8ce9a3_lowercase_discount_code.py
Labels: fix

#6150 fix: returns queried feedback only
  app/api/feedbacks.py
  app/api/schema/users.py
Labels: fix

#6121 feat: Implementation of event invoice generation & calculation
  app/__init__.py
  app/api/helpers/event_invoices.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/storage.py
  app/models/event.py
  app/templates/pdf/event_invoice.html
Labels: feature

#6156 fix: Fixes attendee ticket attachments & email
  app/api/orders.py
Labels: fix

#6154 fix: allows hard delete for feedbacks
  app/api/feedbacks.py
  app/api/helpers/feedback.py
  app/api/schema/feedbacks.py
Labels: fix

#6048 feat: adds checks for owner role invite
  app/api/helpers/role_invite.py
  app/api/role_invites.py
Labels: Priority: URGENT, feature

#6166 feat: Cron job to mark event invoices as due
  app/__init__.py
  app/api/helpers/scheduled_jobs.py
Labels: feature

#6164 fix: Update password reset email to include token additionally
  app/api/auth.py
  app/api/helpers/system_mails.py
Labels: fix

#6176 fix: checks if paid ticket has payment method enabled
  app/api/tickets.py
  app/models/event.py
Labels: fix

#6178 fix: allow event managers to delete expired orders
  app/api/orders.py
Labels: Priority: URGENT, fix

#6182 fix: allow coorganizer, owner to download invoice/tickets for event orders
  app/models/user.py
Labels: fix

#6183 fix: allow coorg, owner to download invoice/tickets for event orders …
  app/models/user.py
Labels: fix

#6140 feat: restricts unverified user for buying free tickets
  app/api/attendees.py
  app/api/orders.py
Labels: feature

#6184 fix: order deletion triggers emails
  app/api/orders.py
Labels: fix

#6145 feat: Serving event invoices through a protected route
  app/api/auth.py
Labels: feature

#6163 feat: add a resend email route for organizers
  app/api/auth.py
Labels: feature

#6188 fix: Add citext extension in migration if not exists
  migrations/versions/ba651e8ce9a3_lowercase_discount_code.py
Labels: fix, hotfix

#6189 fix: Add citext extension in migration if not exists (#6188)
  migrations/versions/ba651e8ce9a3_lowercase_discount_code.py
Labels: fix

#6190 fix: allows only owner and organizer to delete role-invites
  app/api/role_invites.py
Labels: fix

#6196 feat: Add required fields for merge of invoices & order models
  app/api/schema/orders.py
  app/models/order.py
  migrations/versions/5b5cec07a402_.py
Labels: feature

#6203 fix: Making Event Name mandatory for publishing of event
  app/api/events.py
Labels: fix

#6206 fix: handle padding error for verification token
  app/api/auth.py
Labels: fix

#6199 feat: Added order foreign keys & relationships in API
  app/api/__init__.py
  app/api/schema/event_invoices.py
  app/api/schema/orders.py
  app/models/event_invoice.py
  app/models/order.py
  migrations/versions/facee76912bc_.py
Labels: feature

#6209 feat: add field for email exception in speaker schema
  app/api/helpers/scheduled_jobs.py
  app/api/schema/speakers.py
  app/api/sessions.py
  app/api/speakers.py
  app/models/speaker.py
  migrations/versions/96bca587b3ca_.py
Labels: feature

#6219 chore: Remove sudo tag from travis config
  .travis.yml
Labels: chore

#6220 fix: state logic error in sessions.py
  app/api/schema/sessions.py
Labels: fix

#6216 chore: Migrate to flask_jwt_extended
  app/__init__.py
  app/api/admin_statistics_api/events.py
  app/api/attendees.py
  app/api/auth.py
  app/api/discount_codes.py
  app/api/events.py
  app/api/exports.py
  app/api/feedbacks.py
  app/api/helpers/export_helpers.py
  app/api/helpers/import_helpers.py
  app/api/helpers/jwt.py
  app/api/helpers/permission_manager.py
  app/api/helpers/permissions.py
  app/api/helpers/ticketing.py
  app/api/import_jobs.py
  app/api/imports.py
  app/api/orders.py
  app/api/sessions.py
  app/api/settings.py
  app/api/tickets.py
  app/api/uploads.py
  app/api/user_favourite_events.py
  app/api/users.py
  requirements/common.txt
  tests/all/integration/api/helpers/test_jwt.py
  tests/all/integration/api/helpers/test_permission_manager.py
Labels: chore, refactor

#6208 fix: Same discount and access codes cannot be applied to two different events
  app/api/__init__.py
  app/api/access_codes.py
  app/api/discount_codes.py
  docs/api/api_blueprint.apib
  tests/hook_main.py
Labels: fix

#6222 refactor: Rewrite empty_string & add more test cases
  app/api/helpers/utilities.py
  tests/all/integration/api/helpers/test_utilities.py
  tests/all/unit/api/helpers/test_utilities.py
Labels: chore, refactor

#6226 chore: Moved utility unit tests to appropriate folder
  tests/all/integration/api/helpers/test_utilities.py
  tests/all/unit/api/helpers/test_utilities.py
Labels: chore, refactor

#6230 docs: Update order expiry time Admin Only tag
  docs/api/api_blueprint.apib
Labels: docs

#6218 fix: restoration of deleted event
  app/api/events.py
  app/api/schema/events.py
  tests/all/integration/api/validation/test_events.py
Labels: fix

#6233 fix: Replaced hardcoded with FE URL from settings
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
Labels: fix

#6238 fix: Make discount code & access code API URLs follow json api conventions
  app/api/__init__.py
  docs/api/api_blueprint.apib
  tests/hook_main.py
Labels: fix

#6228 fix: send mail only if SMTP was configured(Event Export)
  app/api/helpers/tasks.py
Labels: fix

#6241 fix: add tax information in event copy action
  app/api/event_copy.py
Labels: fix

#6237 chore(deps): Including python-dotenv in requirements
  requirements.txt
  requirements/common.txt
Labels: dependencies

#6251 feat: Make discount codes & access codes support event_identifiers
  app/api/__init__.py
  app/api/access_codes.py
  app/api/discount_codes.py
Labels: Priority: URGENT, feature

#6254 feat: verify unverified user if he resets password
  app/api/auth.py
Labels: feature

#6257 chore: Release v1.4.0
  .travis.yml
  app/__init__.py
  app/api/__init__.py
  app/api/access_codes.py
  app/api/admin_statistics_api/events.py
  app/api/attendees.py
  app/api/auth.py
  app/api/discount_codes.py
  app/api/event_copy.py
  app/api/events.py
  app/api/exports.py
  app/api/feedbacks.py
  app/api/helpers/export_helpers.py
  app/api/helpers/import_helpers.py
  app/api/helpers/jwt.py
  app/api/helpers/mail.py
  app/api/helpers/permission_manager.py
  app/api/helpers/permissions.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/system_mails.py
  app/api/helpers/tasks.py
  app/api/helpers/ticketing.py
  app/api/helpers/utilities.py
  app/api/import_jobs.py
  app/api/imports.py
  app/api/orders.py
  app/api/role_invites.py
  app/api/schema/event_invoices.py
  app/api/schema/events.py
  app/api/schema/orders.py
  app/api/schema/sessions.py
  app/api/schema/speakers.py
  app/api/sessions.py
  app/api/settings.py
  app/api/speakers.py
  app/api/tickets.py
  app/api/uploads.py
  app/api/user_favourite_events.py
  app/api/users.py
  app/models/event_invoice.py
  app/models/order.py
  app/models/speaker.py
  docker-compose-dev.yaml
  docs/api/api_blueprint.apib
  migrations/versions/96bca587b3ca_.py
  migrations/versions/facee76912bc_.py
  requirements.txt
  requirements/common.txt
  tests/all/integration/api/helpers/test_jwt.py
  tests/all/integration/api/helpers/test_permission_manager.py
  tests/all/integration/api/helpers/test_utilities.py
  tests/all/integration/api/validation/test_events.py
  tests/all/unit/api/helpers/test_utilities.py
  tests/hook_main.py
Labels: chore

#6267 fix: Use correct kwarg for access-codes api
  app/api/__init__.py
  app/api/access_codes.py
Labels: fix

#6186 fix: removes discrepancies in cancelling order
  app/api/helpers/notification.py
  app/api/orders.py
Labels: fix

#6264 fix: Add missing api user role relationship links and model definition
  app/api/__init__.py
  app/api/events.py
  app/api/schema/users.py
Labels: fix

#6269 feat: add billing info mandatory field to event model
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/2504915ffd08_.py
Labels: feature

#6261 docs: Correct endpoint Url for creation of Ticket Discount Code in Docs.
  docs/api/api_blueprint.apib
Labels: docs

#6274 fix: Call before_get_method in methods
  app/api/custom_forms.py
  app/api/custom_system_roles.py
  app/api/events.py
  app/api/feedbacks.py
Labels: fix

#6246 fix: updates validate_date check for publishing draft event
  app/api/events.py
Labels: fix

#6277 fix: Stripe publishable key should be accessible to non-admin user
  app/api/schema/events.py
  app/api/schema/stripe_authorization.py
  app/api/stripe_authorization.py
Labels: Priority: URGENT

#6278 chore: Release v1.5.0
  .github/release-drafter.yml
  app/api/__init__.py
  app/api/access_codes.py
  app/api/custom_forms.py
  app/api/custom_system_roles.py
  app/api/events.py
  app/api/feedbacks.py
  app/api/helpers/notification.py
  app/api/orders.py
  app/api/schema/events.py
  app/api/schema/stripe_authorization.py
  app/api/schema/users.py
  app/api/stripe_authorization.py
  app/models/event.py
  docs/api/api_blueprint.apib
  migrations/versions/2504915ffd08_.py
  requirements/common.txt
Labels: chore
