Repository fossasia/open-event-server, pull requests merged in 2019-11, with the labels that each got.

#6561 chore(docs): Remove broken docker deploy button
  README.md
Labels: docs

#6566 fix: Checks for is_email_overridden not working
  app/api/speakers.py
Labels: fix

#6568 chore(docs): Fix grammatical mistakes in docs
  docs/installation/local.md
Labels: docs

#6580 fix: Error while running `python3 manage.py list_routes`
  manage.py
Labels: fix

#6596 chore(docs): Add missing attendee endpoints
  docs/api/blueprint/attendees.apib
  tests/hook_main.py
Labels: docs

#6602 chore(docs): Added auth/verify-email endpoint in documentation
  docs/api/blueprint/auth/email_verification.apib
  tests/hook_main.py
Labels: docs

#6604 fix: handelled invalid price value in paid tickets
  app/api/schema/tickets.py
Labels: fix

#6612 chore: Release v1.8.0
  CHANGELOG.md
  README.md
  app/api/helpers/jwt.py
  app/api/schema/tickets.py
  app/api/server_version.py
  app/api/speakers.py
  app/models/event.py
  app/models/ticket.py
  docs/api/blueprint/attendees.apib
  docs/api/blueprint/auth/email_verification.apib
  docs/api/blueprint/order/orders.apib
  docs/installation/local.md
  manage.py
  migrations/versions/rev-2019-10-18-15:36:50-9effd270a6ae_association_table_name_change.py
  requirements/common.txt
  tests/all/integration/api/helpers/test_auth.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/all/integration/api/helpers/test_db.py
  tests/all/integration/api/helpers/test_errors.py
  tests/all/integration/api/helpers/test_events.py
  tests/all/integration/api/helpers/test_exceptions.py
  tests/all/integration/api/helpers/test_export_helpers.py
  tests/all/integration/api/helpers/test_files.py
  tests/all/integration/api/helpers/test_filters.py
  tests/all/integration/api/helpers/test_jwt.py
  tests/all/integration/api/helpers/test_log.py
  tests/all/integration/api/helpers/test_order.py
  tests/all/integration/api/helpers/test_storage.py
  tests/all/integration/api/helpers/test_systemnotifications.py
  tests/all/integration/api/helpers/test_user.py
  tests/all/integration/api/helpers/test_xcal.py
  tests/all/integration/api/validation/test_access_codes.py
  tests/all/integration/api/validation/test_discount_codes.py
  tests/all/integration/api/validation/test_sessions.py
  tests/all/integration/api/validation/test_speakers_call.py
  tests/all/integration/api/validation/test_tickets.py
  tests/all/integration/test_migrations.py
  tests/hook_main.py
Labels: chore

#6447 feat: Addition and Updation of billing related fields
  app/api/orders.py
  app/models/event.py
  app/models/order.py
  migrations/versions/rev-2019-09-15-08:29:32-d1c2b8711223_.py
Labels: enhancement, feature

#6610 chore(refactor): Refactor code for custom orders route
  app/__init__.py
  app/api/auth.py
  app/api/custom/orders.py
Labels: chore, refactor

#6624 fix: Remove upcoming events from after event email text
  app/api/helpers/mail.py
  app/api/helpers/query.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/system_mails.py
Labels: fix

#6581 fix: Check user permission before exporting
  app/api/exports.py
  app/api/helpers/permissions.py
Labels: fix

#6627 fix: Removed decorator from stripe-authorizations
  app/api/stripe_authorization.py
Labels: fix

#6615 chore(refactor): Make separate blueprint for events and orders
  app/__init__.py
  app/api/custom/invoices.py
  app/api/custom/orders.py
Labels: chore, refactor

#6630 chore: Prepare for release 1.9.0
  CHANGELOG.md
  app/api/server_version.py
Labels: chore

#6631 chore: Release 1.9.0
  CHANGELOG.md
  app/__init__.py
  app/api/auth.py
  app/api/custom/invoices.py
  app/api/custom/orders.py
  app/api/exports.py
  app/api/helpers/mail.py
  app/api/helpers/permissions.py
  app/api/helpers/query.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/system_mails.py
  app/api/orders.py
  app/api/server_version.py
  app/api/stripe_authorization.py
  app/models/event.py
  app/models/order.py
  migrations/versions/rev-2019-09-15-08:29:32-d1c2b8711223_.py
  requirements/common.txt
Labels: chore

#6633 chore: Remove cruft and simplify Dockerfile
  Dockerfile
  requirements/common.txt
Labels: chore

#6611 fix: checksum.py for PayTM
  app/api/helpers/checksum.py
Labels: fix

#6634 fix: Removing is_ticketing_enabled from event models
  app/api/events.py
  app/api/schema/events.py
  app/api/tickets.py
  docs/api/blueprint/event/events.apib
  tests/hook_main.py
Labels: fix
