Repository fossasia/open-event-server, pull requests merged in 2019-09, with the labels that each got.

#6429 fix: Removing currency symbol filter
  app/templates/pdf/attendees_pdf.html
  app/templates/pdf/orders.html
Labels: fix

#6435 feat: add custom form json column to sessions, speaker, attendees
  app/api/helpers/validations.py
  app/api/schema/attendees.py
  app/api/schema/sessions.py
  app/api/schema/settings.py
  app/api/schema/speakers.py
  app/models/session.py
  app/models/setting.py
  app/models/speaker.py
  app/models/ticket_holder.py
  migrations/versions/rev-2019-09-02-09:34:18-7c32ba647a18_.py
  tests/all/integration/api/validation/test_sessions.py
Labels: feature

#6410 chore(deps): Update pycrypto to fork
  requirements/common.txt
Labels: dependencies

#6361 fix: should not return fields related to a deleted field
  app/api/helpers/db.py
Labels: fix

#6454 feat: Remove Python style object base from classes
  app/__init__.py
  app/api/helpers/payment.py
  app/api/helpers/storage.py
  app/api/helpers/third_party_auth.py
  app/api/helpers/ticketing.py
  app/api/helpers/utilities.py
  config.py
Labels: feature

#6466 refactor: Convert TicketHolder Model Def to dataclass
  .travis.yml
  app/models/ticket_holder.py
Labels: chore, refactor

#6474 chore: Add correct release info in README
  README.md
Labels: chore

#6473 feat: Integrate sqlalchemy, redis and celery in sentry
  app/__init__.py
Labels: feature

#6475 fix: Revert dredd to 4.0.0
  .travis.yml
  dredd.yml
Labels: fix

#6476 chore: Add dredd GitHub action
  .github/workflows/dredd.yml
Labels: chore
