Repository fossasia/open-event-server, pull requests merged in 2019-08, with the labels that each got.

#6285 fix: add missing current_user import in ticketing helper
  app/api/helpers/ticketing.py
Labels: Priority: URGENT, fix

#6286 chore: Baseline master into dev
  app/api/helpers/ticketing.py
Labels: chore

#6295 fix: remove deleted events from cron actions
  app/api/helpers/scheduled_jobs.py
Labels: fix

#6055 fix: enable discount code checks for over consumption
  app/api/helpers/ticketing.py
  app/api/orders.py
Labels: fix

#6204 feat: Implement Refresh Tokens
  app/__init__.py
  app/api/auth.py
  app/api/helpers/auth.py
  app/api/users.py
  app/models/user_token_blacklist.py
  migrations/alembic.ini
  migrations/versions/rev-2019-08-03-05:18:10-4925dd5fd720_add_user_token_blacklist_time_table.py
Labels: feature

#6299 fix: avoid check if email is overridden
  app/api/speakers.py
  docs/api/api_blueprint.apib
Labels: fix

#6301 docs: Add API docs for refresh token implementation
  docs/api/blueprint/auth/authentication.apib
  tests/hook_main.py
Labels: docs

#6292 fix: event invoice to be accessed by identifier
  app/api/__init__.py
  app/api/discount_codes.py
  app/api/event_invoices.py
  app/api/events.py
  app/api/helpers/permission_manager.py
  app/api/users.py
Labels: fix

#6270 fix: orders with amount>0 cannot be completed without payment
  app/api/orders.py
Labels: fix

#6313 feat: Added date to order invoice
  app/templates/pdf/order_invoice.html
Labels: feature

#6294 fix: Unverified user can buy free tickets
  app/api/attendees.py
Labels: fix

#6307 fix: Fix valid choices for invoices schema
  app/api/schema/event_invoices.py
Labels: fix

#6324 fix: use from email name for sendgrid emails
  app/api/helpers/tasks.py
Labels: fix

#6265 feat: Design Event Invoice Template
  app/api/helpers/scheduled_jobs.py
  app/models/event.py
  app/templates/pdf/event_invoice.html
Labels: feature

#6192 fix: make billing info mandatory for paid orders
  app/api/orders.py
Labels: fix

#6331 fix: changed storage paths to fix mail bug
  app/api/helpers/order.py
  app/api/orders.py
Labels: fix

#6322 feat: add stripe test key fields to settings model
  app/api/helpers/payment.py
  app/api/schema/settings.py
  app/factories/setting.py
  app/models/setting.py
  migrations/versions/rev-2019-08-07-01:11:29-f5c3a4fd23fb_.py
Labels: feature

#6329 fix: Implement nested tables in order invoice details
  app/templates/pdf/order_invoice.html
Labels: fix

#6287 feat: Added function for previous month's ticket sales count
  app/models/event.py
Labels: feature

#6334 fix: Fixed function pertaining to previous month's ticket sales
  app/models/event.py
Labels: fix

#6310 fix: check for paid orders to show billing info
  app/api/orders.py
Labels: fix, hotfix

#6338 fix: adds unique session and user constraint to feedback model
  app/models/feedback.py
  migrations/versions/rev-2019-08-10-00:08:43-9d5753192ac9_.py
Labels: fix

#6335 feat: send notification to coorganizers - ticket sales
  app/api/orders.py
Labels: feature

#6328 fix: Return only accepted session and public speaker call by default
  app/api/sessions.py
  app/api/speakers_calls.py
Labels: fix

#6249 feat: Model additions for payTM integration
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/rev-2019-08-09-19:41:03-246b5b6123af_.py
Labels: feature

#6344 fix: check for case where client sends null for max_quantity
  app/api/schema/discount_codes.py
Labels: Priority: URGENT, fix

#6336 fix: order updation without 'amount' key works
  app/api/orders.py
Labels: fix, hotfix

#6351 fix: Duplicate entries allowed in Ticket-Tag
  app/models/ticket.py
  migrations/versions/rev-2019-08-13-14:38:26-1bdf23be63bd_.py
Labels: fix

#6357 fix: remove additional parameters for is_paytm_activated(schema)
  app/api/schema/settings.py
Labels: fix

#6346 fix: Typo in the notification invitation message
  app/api/helpers/system_notifications.py
Labels: fix

#6349 feat: add can_pay_by_paytm to event model and schema and refactor other keys
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2019-08-13-13:24:45-d252c86d0200_.py
Labels: feature

#6359 fix: Use ==/!= to compare str, bytes, and int literals
  app/api/helpers/files.py
Labels: fix

#6358 feat: Addition of stripe test client id
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/rev-2019-08-13-16:07:52-cd3beca1951a_.py
Labels: feature

#6281 fix: Add server checks for ticket price
  app/api/tickets.py
Labels: fix

#6296 feat: Implemented routes for creation & charging(invoice) through PayPal
  app/api/event_invoices.py
Labels: feature

#6370 feat: Support for non-attachment mails
  app/api/helpers/tasks.py
Labels: feature

#6373 chore: Upgrade dredd and increase hooks timeout
  .travis.yml
  dredd.yml
Labels: chore

#6376 chore(deps): Downgrade to dredd 11.0.0
  .travis.yml
Labels: dependencies

#6380 chore: Preload gunicorn to share memory and perf
  scripts/container_start.sh
Labels: chore

#6369 fix: remove pending from default invoice status
  app/models/event_invoice.py
  migrations/versions/rev-2019-08-17-16:59:44-90d62fe3b5e3_change_pending_invoices.py
Labels: fix

#6387 chore: Push Build only for Master or Development
  .travis.yml
Labels: chore

#6297 feat: Add paypal configuration for Android Paypal Payment
  app/api/helpers/payment.py
  app/api/orders.py
Labels: feature

#6386 fix: Delete duplicate ticket tags
  migrations/versions/rev-2019-08-13-14:38:26-1bdf23be63bd_.py
  migrations/versions/rev-2019-08-17-20:46:39-9172ceb350b8_duplicate_ticket_tag.py
Labels: fix

#6391 feat: update event invoice payment follow ups
  app/__init__.py
  app/api/helpers/scheduled_jobs.py
Labels: feature

#6398 fix: Unique ticket tag migration not being called
  migrations/versions/rev-2019-08-13-14:38:26-1bdf23be63bd_.py
Labels: fix

#6342 feat: Adds transaction initiation logic & Payments Manager - PayTM
  app/api/helpers/checksum.py
  app/api/helpers/payment.py
  app/api/orders.py
  app/api/schema/orders.py
  requirements/common.txt
Labels: feature

#6395 fix: error and pointer for unverified user buying free tickets
  app/api/orders.py
Labels: fix

#6406 fix: Configure PayPal for mobile payments
  app/api/helpers/payment.py
Labels: fix

#6412 fix: Comparison cast for paypal payment verification
  app/api/helpers/payment.py
Labels: fix

#6399 feat: Transaction Processing logic & Wallet linking implementation
  app/api/helpers/payment.py
  app/api/orders.py
Labels: feature

#6415 chore: Make docker-compose production ready
  docker-compose-dev.yaml
  docker-compose-dev.yml
  docker-compose.yml
  postgres-initdb.d/create_db.sql
  scripts/container_start.sh
  scripts/wait-for.sh
Labels: chore

#6417 fix: Add save_to_db in payment.py
  app/api/helpers/payment.py
Labels: fix

#6425 fix: Fix the url for all the exports
  app/api/helpers/storage.py
  tests/all/integration/api/helpers/test_storage.py
Labels: fix

#6366 feat: API to fetch total order amount by passing tickets and discount code
  app/api/auth.py
  app/api/helpers/order.py
  app/api/helpers/ticketing.py
  app/api/orders.py
Labels: feature

#6402 feat: endpoint to fetch transaction status of an order via paytm
  app/api/orders.py
Labels: feature

#6431 feat: Added JWT headers to fix accessibility issue
  app/api/orders.py
Labels: feature
