Repository fossasia/open-event-server, pull requests merged in 2019-05, with the labels that each got.

#5856 fix: make paypal helper syntax backward compatible
  app/api/helpers/payment.py
Labels: fix

#5853 fix: add space in notification template
  app/api/helpers/system_notifications.py
Labels: fix

#5840 feat: Create a scheduled job for changing session status on event completion
  app/__init__.py
  app/api/helpers/scheduled_jobs.py
Labels: feature

#5843 fix: allow sessions without speakers to be created
  app/api/sessions.py
Labels: fix

#5835 fix: allow patch request in the case when the session is being created
  app/api/helpers/permission_manager.py
Labels: fix

#5826 fix: Allow a non-admin speaker to handle his speaker details
  app/api/helpers/permission_manager.py
  app/api/speakers.py
Labels: fix

#5860 feat: add omise credential columns
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/a0532f339abb_.py
Labels: feature

#5863 fix: Add can_pay_by_omise field in event schema
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/6f7b6fad3f53_add_can_pay_by_omise_in_event_model.py
Labels: fix

#5869 fix: set default value of amount in possible error cases
  app/api/schema/orders.py
Labels: fix

#5873 docs: Update redis package name for RH based Linux distributions
  docs/installation/local.md
Labels: docs

#5733 fix: elasticsearch has no attribute sync
  app/views/elastic_cron_helpers.py
Labels: fix

#5514 fix: event import
  app/api/__init__.py
  app/api/helpers/import_helpers.py
  app/api/import_jobs.py
  app/api/imports.py
  app/api/schema/import_jobs.py
  app/models/event.py
  docs/api/api_blueprint.apib
Labels: fix

#5867 fix: Make copied event sponsor logo url generation a celery task
  app/api/event_copy.py
  app/api/helpers/tasks.py
Labels: fix

#5884 fix: Send order email post completion
  app/api/orders.py
Labels: Priority: URGENT, fix

#5887 feat: create scheduled task for expiring pending tickets
  app/__init__.py
  app/api/helpers/scheduled_jobs.py
Labels: feature

#5886 fix: Made ticket invoice generation similar to tickets
  app/api/auth.py
  app/api/helpers/order.py
  app/api/helpers/storage.py
  app/templates/pdf/order_invoice.html
Labels: fix

#5909 fix: adds migration to change type of gender field in custom form to select
  migrations/versions/6f7bfad3f54_update_gender_type_in_custom_form.py
Labels: fix

#5824 fix: implement checks on deleting an event
  app/api/events.py
Labels: fix

#5902 chore: update sqlchemy dependency
  Pipfile
  Pipfile.lock
  app/api/admin_sales/locations.py
  requirements/common.txt
Labels: chore

#5914 fix: Add completed_at date for no charge orders
  app/api/orders.py
Labels: fix

#5916 fix: Sync Pipfile.lock
  Pipfile.lock
Labels: fix

#5882 feat: ability to delete user's account by himself/herself
  app/api/users.py
Labels: feature

#5892 fix: Multiple redirections for tickets
  app/api/auth.py
Labels: fix

#5917 feat: Attaching tickets+invoice to order emails
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/helpers/tasks.py
  app/api/orders.py
  requirements/common.txt
Labels: feature

#5928 chore: Move Pipfile and Pipfile.lock
  .Pipfile
  .Pipfile.lock
Labels: chore

#5935 fix: restore labels for unlabelled fields in sessions/speakers by refactoring legacy data
  migrations/versions/6f7b6fad3f55_refactor_customform_identifiers.py
Labels: Priority: URGENT, fix

#5926 fix: update scheduler time constraint for pending tickets
  app/api/helpers/order.py
  app/api/helpers/scheduled_jobs.py
  app/api/orders.py
  app/api/schema/orders.py
  app/factories/order.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/all/integration/api/helpers/test_order.py
Labels: fix

#5941 fix: remove recent ticket and speaker_call schema checks
  app/api/schema/speakers_calls.py
  app/api/schema/tickets.py
  tests/all/integration/api/validation/test_speakers_call.py
  tests/all/integration/api/validation/test_tickets.py
Labels: fix

#5944 chore: Change requirements syntax and upgrade celery
  app/__init__.py
  app/api/helpers/tasks.py
  requirements/common.txt
  requirements/dev.txt
  requirements/tests.txt
Labels: chore

#5948 fix: Use SQLAlchemy in-built timestamp function
  app/models/session.py
  app/models/user.py
Labels: fix

#5942 fix: Add access-control for admin-specific route
  app/__init__.py
  app/api/auth.py
Labels: fix

#5957 fix: placed orders generate local tickets
  app/api/helpers/order.py
Labels: fix

#5931 feat: Implement locking a session feature by organizer
  app/api/schema/sessions.py
  app/api/sessions.py
  app/models/session.py
  migrations/versions/b3bfa7949acf_.py
Labels: feature

#5967 chore: implement new sentry sdk and remove raven dependency
  app/__init__.py
  app/api/events.py
  app/views/healthcheck.py
  app/views/sentry.py
  requirements/common.txt
Labels: chore

#5974 chore: 'werkzeug.contrib.profiler' has moved to 'werkzeug.middleware.profiler'
  app/__init__.py
Labels: chore
