Repository fossasia/open-event-server, pull requests merged in 2019-12, with the labels that each got.

#6636 chore: disable elasticsearch in .env.example
  .env.example
Labels: chore

#6628 fix: Allow tickets to have same name as deleted ones
  app/models/ticket.py
  migrations/versions/rev-2019-12-04-00:37:24-0223c881d135_.py
Labels: fix

#6639 fix: Use requests to fetch event and speaker images
  app/api/helpers/files.py
  docs/api/blueprint/user/users.apib
Labels: fix

#6645 feat: management command to resize images of events and speakers
  app/api/helpers/tasks.py
  manage.py
Labels: feature

#6643 fix: canceled order mail template changed
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
Labels: fix

#6648 fix: caught invalid url image exception in resize image tasks
  app/api/helpers/tasks.py
  manage.py
Labels: fix

#6649 fix: changed safequery to normal query in resize image task
  app/api/helpers/tasks.py
Labels: fix

#6658 chore: Remove flask limiter warning
  app/__init__.py
  app/api/auth.py
  app/api/custom/orders.py
Labels: chore

#6660 feat: add created_at, modified_at in ticket_holder
  app/models/ticket_holder.py
  migrations/versions/rev-2019-12-13-20:34:35-8621f70992ba_.py
Labels: feature

#6663 chore: Populate flask shell context
  app/__init__.py
  app/extensions/shell.py
Labels: chore

#6656 feat: Optimize link generation
  app/api/schema/__init__.py
  app/api/schema/users.py
Labels: feature

#6667 chore: Remove slow/unused aggregate queries from event schema
  app/api/schema/events.py
  docs/api/blueprint/event/events.apib
Labels: chore

#6683 fix: Order Post route view
  app/api/schema/orders.py
Labels: fix

#6662 feat: add job to delete ticket holders with no order id
  app/__init__.py
  app/api/helpers/scheduled_jobs.py
  app/factories/attendee.py
  tests/all/integration/api/helpers/test_scheduled_jobs.py
Labels: feature

#6688 chore: Prepare for v1.10.0
  CHANGELOG.md
  app/api/server_version.py
Labels: chore

#6687 chore: Release v1.10.0
  .env.example
  CHANGELOG.md
  Dockerfile
  app/__init__.py
  app/api/auth.py
  app/api/custom/orders.py
  app/api/events.py
  app/api/helpers/checksum.py
  app/api/helpers/files.py
  app/api/helpers/mail.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/system_mails.py
  app/api/helpers/tasks.py
  app/api/schema/__init__.py
  app/api/schema/events.py
  app/api/schema/orders.py
  app/api/schema/users.py
  app/api/server_version.py
  app/api/tickets.py
  app/extensions/shell.py
  app/factories/attendee.py
  app/models/ticket.py
  app/models/ticket_holder.py
  docs/api/blueprint/event/events.apib
  docs/api/blueprint/user/users.apib
  manage.py
  migrations/versions/rev-2019-12-04-00:37:24-0223c881d135_.py
  migrations/versions/rev-2019-12-13-20:34:35-8621f70992ba_.py
  requirements/common.txt
  requirements/tests.txt
  runtime.txt
  tests/all/integration/api/helpers/test_scheduled_jobs.py
  tests/hook_main.py
Labels: chore

#6690 chore: run container script run through CLI args
  Dockerfile
  docker-compose.yml
  scripts/container_start.sh
Labels: chore

#6573 fix: Order of any kind should not be deleted except by admin
  app/api/orders.py
Labels: fix

#6693 fix: count query of sold tickets
  app/api/attendees.py
  app/factories/attendee.py
  app/models/order.py
  tests/all/integration/api/helpers/test_order.py
Labels: fix

#6696 feat: run docker container as non root user
  Dockerfile
  docker-compose.yml
Labels: feature

#6699 fix: missing field and incorrect column value in session csv export
  app/api/helpers/csv_jobs_util.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
Labels: fix
