Repository fossasia/open-event-server, pull requests merged in 2019-04, with the labels that each got.

#5757 test: Add make_filename unit test for export_helpers.
  tests/all/unit/api/helpers/test_export_helpers.py
Labels: testing

#5763 chore: Translation link change
  app/api/admin_translations.py
Labels: chore

#5770 fix: Enable updating deletedAt for user by admin
  app/api/users.py
Labels: fix

#5781 fix: condition for restoring deleted users
  app/api/users.py
Labels: fix

#5776 fix: session slides saving error
  app/api/sessions.py
Labels: fix

#5783 fix: Event Feedback List made accessible to everyone
  app/api/feedbacks.py
Labels: fix

#5767 fix: Translation Downloads deletion fix(celery)
  app/api/admin_translations.py
Labels: fix

#5769 fix: Make wrong current password error message more informative.
  app/api/auth.py
Labels: fix

#5755 fix: Add ticket relationship to access_code model
  app/models/access_code.py
  migrations/versions/5551af72812f_.py
Labels: fix

#5814 fix: Made EventFAQs List accessible to everyone
  app/api/faqs.py
Labels: fix

#5799 docs(api): adds fields related to billing to orders API
  docs/api/api_blueprint.apib
Labels: documentation

#5801 fix: Add check for ticket and CFS ends-at
  app/api/schema/speakers_calls.py
  app/api/schema/tickets.py
  tests/all/integration/api/validation/test_speakers_call.py
  tests/all/integration/api/validation/test_tickets.py
Labels: fix

#5754 test: Add AccessCode validation tests
  app/factories/access_code.py
  tests/all/integration/api/validation/test_access_codes.py
  tests/all/integration/api/validation/test_discount_codes.py
Labels: testing

#5785 test: Add unit test for handle_unserializable_data present in export_helpers
  tests/all/unit/api/helpers/test_export_helpers.py
Labels: testing

#5803 fix: use current_identity as user's email
  app/api/helpers/export_helpers.py
Labels: fix

#5816 fix: Amount to zero if amount not present(order api)
  app/api/orders.py
Labels: fix

#5818 fix: Admin translations security
  app/api/admin_translations.py
Labels: fix

#5820 feat: add server code for is_featured column
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/e59e7a75f679_.py
Labels: feature

#5790 fix: Ticket security bug fix & flow refactoring
  .gitignore
  app/__init__.py
  app/api/auth.py
  app/api/helpers/files.py
  app/api/helpers/order.py
  app/api/helpers/storage.py
Labels: fix

#5800 test: Add tests for import_helpers
  tests/all/unit/api/helpers/test_import_helpers.py
Labels: testing

#5833 docs(api): Update docs for Event Feedback and FAQ
  docs/api/api_blueprint.apib
Labels: api, docs

#5830 fix: Fixes the incomplete path of ticket downloads
  app/api/auth.py
  app/api/helpers/files.py
  app/api/helpers/storage.py
Labels: fix

#5806 docs(api): adds missing params from user docs
  docs/api/api_blueprint.apib
Labels: docs

#5789 test: Add test for generate_hash and upload_local in storage helpers.
  tests/all/integration/api/helpers/test_storage.py
  tests/all/unit/api/helpers/test_storage.py
Labels: testing

#5839 refactor: Change url_prefix for tickets route
  app/api/auth.py
Labels: chore, refactor

#5846 fix: Number of sessions(based on state) shown correctly
  app/api/schema/event_statistics.py
Labels: fix

#5834 test: Added integration and unit tests for Errors base class
  tests/all/integration/api/helpers/test_errors.py
  tests/all/unit/api/helpers/test_errors.py
Labels: testing

#5852 fix: Fetch correct paypal credentials when in production
  app/api/helpers/payment.py
Labels: Priority: URGENT, fix
