Repository fossasia/open-event-server, pull requests merged in 2020-05, with the labels that each got.

#6780 refactor: change return error.respond() to raise
  app/api/auth.py
  app/api/custom/attendees.py
  app/api/custom/invoices.py
  app/api/custom/orders.py
  app/api/event_invoices.py
  app/api/helpers/errors.py
  app/api/helpers/order.py
  app/api/helpers/permission_manager.py
  app/api/helpers/permissions.py
  app/api/orders.py
  app/api/role_invites.py
  app/api/schema/sessions.py
  app/api/schema/tracks.py
  app/api/settings.py
  app/instance.py
  tests/all/integration/api/helpers/test_permission_manager.py
Labels: chore, refactor

#6863 test: Add tests for notification helper functions
  app/api/helpers/notification.py
  app/api/helpers/system_notifications.py
  tests/all/integration/api/helpers/test_notification.py
Labels: testing

#6827 test: Start integrating pytest
  .coveragerc
  .travis.yml
  app/api/helpers/scheduled_jobs.py
  app/models/event.py
  populate_db.py
  requirements/tests.txt
  tests/all/integration/api/helpers/test_auth.py
  tests/all/integration/api/validation/test_created_at.py
  tests/all/unit/api/helpers/test_errors.py
  tests/all/unit/utils/test_schema_defaulting.py
Labels: testing

#6980 chore: Update max line length in .deepsource.toml
  .deepsource.toml
Labels: chore

#6979 test: Use scoped session db
  tests/all/conftest.py
  tests/all/integration/api/helpers/test_auth.py
  tests/all/integration/setup_database.py
  tests/all/unit/utils/test_schema_defaulting.py
  tests/factories/access_code.py
  tests/factories/activities.py
  tests/factories/attendee.py
  tests/factories/base.py
  tests/factories/custom_form.py
  tests/factories/custom_placeholder.py
  tests/factories/custom_system_role.py
  tests/factories/discount_code.py
  tests/factories/email_notification.py
  tests/factories/event.py
  tests/factories/event_copyright.py
  tests/factories/event_invoice.py
  tests/factories/event_location.py
  tests/factories/event_role_permission.py
  tests/factories/event_sub_topic.py
  tests/factories/event_topic.py
  tests/factories/event_type.py
  tests/factories/export_job.py
  tests/factories/faq.py
  tests/factories/faq_type.py
  tests/factories/feedback.py
  tests/factories/image_size.py
  tests/factories/mail.py
  tests/factories/message_setting.py
  tests/factories/microlocation.py
  tests/factories/module.py
  tests/factories/notification.py
  tests/factories/notification_action.py
  tests/factories/order.py
  tests/factories/page.py
  tests/factories/panel_permission.py
  tests/factories/role.py
  tests/factories/role_invite.py
  tests/factories/service.py
  tests/factories/session.py
  tests/factories/session_type.py
  tests/factories/setting.py
  tests/factories/social_link.py
  tests/factories/speaker.py
  tests/factories/speakers_call.py
  tests/factories/sponsor.py
  tests/factories/stripe_authorization.py
  tests/factories/tax.py
  tests/factories/ticket.py
  tests/factories/ticket_fee.py
  tests/factories/ticket_tag.py
  tests/factories/track.py
  tests/factories/user.py
  tests/factories/user_email.py
  tests/factories/user_favourite_events.py
  tests/factories/user_permission.py
  tests/factories/user_token_blacklist.py
Labels: testing

#6981 test: Use nested transactions for all tests
  requirements/tests.txt
  tests/all/integration/api/helpers/test_icalexporter.py
  tests/all/integration/api/helpers/test_notification.py
  tests/all/integration/api/helpers/test_order.py
  tests/all/integration/api/helpers/test_pentabarfxml.py
  tests/all/integration/api/helpers/test_permission_manager.py
  tests/all/integration/api/helpers/test_scheduled_jobs.py
  tests/all/integration/api/validation/test_created_at.py
  tests/all/integration/api/validation/test_discount_codes.py
  tests/all/integration/utils.py
  tests/factories/base.py
Labels: chore

#6720 feat: Endpoint to complete an order in new Orders API
  app/api/custom/orders.py
Labels: feature

#6990 chore(docs): Add OS support in README
  README.md
Labels: docs

#7004 test: Validation of tickets, discount code
  app/api/helpers/db.py
  app/api/helpers/order.py
  app/api/helpers/ticketing.py
  app/api/orders.py
  app/models/discount_code.py
  tests/all/integration/api/helpers/order/test_calculate_order_amount.py
  tests/all/integration/api/helpers/order/test_validate_discount_code.py
  tests/all/integration/api/helpers/order/test_validate_ticket_holders.py
  tests/all/integration/api/helpers/order/test_validate_tickets.py
  tests/all/integration/api/helpers/test_ticketing.py
  tests/factories/discount_code.py
  tests/factories/order.py
Labels: testing

#7007 test: Complete testing of calculate Order amount
  app/api/custom/orders.py
  app/api/helpers/exceptions.py
  app/api/helpers/order.py
  tests/all/conftest.py
  tests/all/integration/api/helpers/order/test_calculate_order_amount.py
Labels: testing

#7012 test: Re-enable discount code creation test
  app/__init__.py
  app/api/discount_codes.py
  docs/api/blueprint/discount_codes.apib
  dredd.yml
  tests/hook_main.py
Labels: testing

#7015 refactor: Deduplicate get_new_slug method
  app/api/helpers/db.py
  app/models/event_location.py
  app/models/event_sub_topic.py
  app/models/event_topic.py
  app/models/event_type.py
Labels: chore, refactor

#7017 refactor: remove repetitive safe_query
  app/api/access_codes.py
  app/api/attendees.py
  app/api/custom_forms.py
  app/api/custom_placeholders.py
  app/api/custom_system_roles.py
  app/api/discount_codes.py
  app/api/email_notifications.py
  app/api/event_copyright.py
  app/api/event_invoices.py
  app/api/event_statistics.py
  app/api/event_sub_topics.py
  app/api/event_topics.py
  app/api/event_types.py
  app/api/events.py
  app/api/faq_types.py
  app/api/faqs.py
  app/api/feedbacks.py
  app/api/helpers/db.py
  app/api/helpers/query.py
  app/api/microlocations.py
  app/api/notifications.py
  app/api/order_statistics/events.py
  app/api/orders.py
  app/api/panel_permissions.py
  app/api/roles.py
  app/api/session_types.py
  app/api/sessions.py
  app/api/speakers.py
  app/api/stripe_authorization.py
  app/api/tax.py
  app/api/ticket_tags.py
  app/api/tickets.py
  app/api/tracks.py
  app/api/user_emails.py
  app/api/user_favourite_events.py
  app/api/users.py
Labels: chore, refactor

#7020 chore(polish): Reformat after safe_query refactor
  app/api/custom_placeholders.py
  app/api/custom_system_roles.py
  app/api/discount_codes.py
  app/api/event_invoices.py
  app/api/event_statistics.py
  app/api/event_sub_topics.py
  app/api/event_topics.py
  app/api/events.py
  app/api/faqs.py
  app/api/helpers/db.py
  app/api/helpers/query.py
  app/api/notifications.py
  app/api/order_statistics/events.py
  app/api/orders.py
  app/api/panel_permissions.py
  app/api/roles.py
  app/api/sessions.py
  app/api/stripe_authorization.py
  app/api/tickets.py
  app/api/users.py
Labels: chore

#7022 chore(refactor): Remove arrow dependency from the project
  app/templates/flask_ext/jinja/filters.py
  requirements/common.txt
  tests/all/integration/api/helpers/test_humanize_helper.py
Labels: chore, refactor

#7032 docs: Add redis start command for macOS
  docs/installation/local.md
Labels: docs

#7033 feat: Group tax in calculate order amount
  app/api/helpers/order.py
  tests/all/integration/api/helpers/order/test_calculate_order_amount.py
Labels: feature

#7034 fix: Allow no tickets amount calculation with discount
  app/api/helpers/order.py
  tests/all/integration/api/helpers/order/test_calculate_order_amount.py
Labels: fix

#7035 fix: Make order amount calculation order agnostic
  app/api/helpers/order.py
  tests/all/integration/api/helpers/order/test_calculate_order_amount.py
Labels: fix
