Repository fossasia/open-event-server, pull requests merged in 2020-09, with the labels that each got.

#7236 chore(docs): Fix broken link to API description
  README.md
Labels: docs

#7243 feat: add patreon_url in settings model
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/rev-2020-09-04-10:49:48-3548da69bdec_.py
Labels: feature

#7244 fix: Add more constraints to upcoming events
  app/api/events.py
Labels: fix

#7251 fix: Let event fields be nullable
  app/api/events.py
  app/api/schema/events.py
  tests/all/integration/api/event/__init__.py
  tests/all/integration/api/event/test_event_patch.py
Labels: fix

#7253 fix: make event refund_policy editable
  app/api/schema/events.py
Labels: fix

#7254 fix: allow refund_policy to be none
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2020-09-10-19168ff996c6_.py
Labels: fix

#7257 chore: Make celery container depend on web
  docker-compose.yml
Labels: chore

#7260 feat: Add more status for event invoice
  app/api/schema/event_invoices.py
Labels: feature

#7216 docs: running using docker modified
  docs/installation/docker.md
Labels: docs

#7261 chore: Enable dredd tests for some of the Orders API endpoints
  app/api/custom/orders.py
  docs/api/blueprint/order/orders.apib
  tests/hook_main.py
Labels: chore

#7263 chore(docs): Adds dredd tests for calculate-amount API
  docs/api/blueprint/order/orders.apib
  tests/hook_main.py
Labels: chore, docs

#7264 chore: Add cron scripts
  scripts/cron/crontab
  scripts/cron/db_backup.sh
  scripts/cron/media_backup.sh
  scripts/cron/monitor
Labels: chore

#7270 fix: User event invoice endpoint
  app/api/schema/users.py
  app/models/event_invoice.py
Labels: fix

#7280 feat: Allow user verification through API request
  app/api/schema/users.py
  app/api/users.py
Labels: feature

#7279 feat: Event Invoice Refactor
  Dockerfile
  app/api/events.py
  app/api/helpers/db.py
  app/api/helpers/files.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/storage.py
  app/api/helpers/system_mails.py
  app/api/schema/event_invoices.py
  app/models/event.py
  app/models/event_invoice.py
  app/models/order.py
  app/models/role_invite.py
  app/models/setting.py
  app/models/user.py
  app/templates/flask_ext/jinja/filters.py
  app/templates/pdf/event_invoice.html
  docs/api/blueprint/discount_codes.apib
  docs/api/blueprint/invoices.apib
  migrations/versions/rev-2020-09-21-08:08:50-3fe3442b7a13_.py
  requirements/common.txt
  tests/all/integration/api/helpers/test_scheduled_jobs.py
  tests/factories/event_invoice.py
Labels: feature

#7284 fix: Round invoice money using decimal
  app/models/event_invoice.py
Labels: fix

#7286 feat: Add admin billing paypal email
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/rev-2020-09-25-11:11:26-8e86e0ddc9a4_.py
Labels: feature

#7287 fix: Use admin billing paypal email for invoice
  app/api/event_invoices.py
  app/api/helpers/payment.py
Labels: fix

#7294 fix: Round money in order/invoice instead of int
  app/api/helpers/payment.py
  app/api/helpers/utilities.py
  app/api/users.py
  app/models/event_invoice.py
Labels: fix

#7295 fix: Make currency optional in ticket fees
  app/api/schema/ticket_fees.py
Labels: fix

#7296 feat: Add all invoice emails in system
  app/api/helpers/mail.py
  app/api/helpers/notification.py
  app/api/helpers/system_mails.py
  app/api/helpers/system_notifications.py
  app/models/event_invoice.py
  app/models/mail.py
  tests/all/integration/api/helpers/test_notification.py
  tests/all/integration/api/helpers/test_systemnotifications.py
Labels: feature

#7299 feat: Allow anonymous links in event description
  app/models/event.py
Labels: feature

#7300 feat: Complete invoice generation
  .travis.yml
  app/api/helpers/payment.py
  app/api/helpers/scheduled_jobs.py
  app/api/schema/event_invoices.py
  app/models/event_invoice.py
  app/templates/pdf/event_invoice.html
  migrations/versions/rev-2020-09-30-12:50:33-08e4b2df44a3_.py
  migrations/versions/rev-2020-09-30-13:00:05-99217a8bc9b2_.py
  tests/all/unit/api/helpers/test_utilities.py
Labels: feature

#7305 fix: Configure paypal on charge request
  app/api/helpers/payment.py
Labels: fix

#7306 fix: Add admin email in BBC for invoice email
  app/api/helpers/mail.py
  app/api/helpers/tasks.py
Labels: fix

#7307 fix: Use UTC as event invoice issued-at timezone
  app/api/helpers/scheduled_jobs.py
Labels: fix
