Repository fossasia/open-event-server, pull requests merged in 2020-12, with the labels that each got.

#7469 fix: Make speaker email nullable
  app/api/helpers/custom_forms.py
  app/api/speakers.py
  app/models/speaker.py
  migrations/versions/rev-2020-11-26-14:16:30-060a77f9a1ea_.py
  tests/all/integration/api/speaker/test_speaker_email_override.py
Labels: fix

#7481 fix: Give access to order tickets and attendees to organizers
  app/api/attendees.py
  app/models/order.py
Labels: fix

#7484 fix: Use identifier for export instead of field identifier
  app/api/helpers/csv_jobs_util.py
  app/templates/pdf/attendees_pdf.html
Labels: fix

#7494 feat: Global event video stream
  app/api/events.py
  app/api/helpers/utilities.py
  app/api/routes.py
  app/api/schema/events.py
  app/api/schema/video_stream.py
  app/api/video_stream.py
  app/models/event.py
  app/models/video_stream.py
  migrations/versions/rev-2020-12-06-06:27:36-19c591aa2ff0_.py
  migrations/versions/rev-2020-12-07-00:34:43-ec00fcbb3994_.py
  tests/all/integration/api/video_stream/test_video_stream_create_api.py
  tests/all/integration/api/video_stream/test_video_stream_edit_api.py
Labels: feature

#7502 feat: allow admin to add organizer logo in event invoice
  app/api/schema/settings.py
  app/models/setting.py
  app/templates/pdf/event_invoice.html
  migrations/versions/rev-2020-12-10-13:19:11-447e39dd5fc2_.py
Labels: feature

#7501 feat: Add video channels integration
  app/api/helpers/db.py
  app/api/routes.py
  app/api/schema/video_channel.py
  app/api/schema/video_stream.py
  app/api/video_channel.py
  app/models/video_channel.py
  app/models/video_stream.py
  migrations/versions/rev-2020-12-07-00:34:43-ec00fcbb3994_.py
  migrations/versions/rev-2020-12-10-05:14:25-295e44c2202b_.py
  migrations/versions/rev-2020-12-10-05:21:29-f6bd6bce0205_.py
  populate_db.py
  tests/all/integration/api/validation/test_created_at.py
  tests/factories/video_channel.py
Labels: feature

#7500 fix: making track optional
  app/api/sessions.py
Labels: fix

#7505 chore: Add API key in Video Channel
  app/api/schema/video_channel.py
  app/api/schema/video_stream.py
  app/models/video_channel.py
  app/models/video_stream.py
  migrations/versions/rev-2020-12-11-08:51:44-73dad592fcd6_.py
Labels: chore

#7470 fix: ticket sold out event page restriction
  app/api/events.py
Labels: fix

#7499 fix: don't allow session edit after session is held
  app/api/sessions.py
Labels: fix

#7506 feat: Integrate BBB video channel
  app/api/schema/video_stream.py
  app/api/video_channels/bbb.py
  app/api/video_stream.py
  app/instance.py
  app/models/video_channel.py
  requirements/common.txt
  tests/factories/common.py
Labels: feature

#7507 fix: event start time can be before current
  app/api/events.py
Labels: fix

#7512 fix: Create BBB meeting on stream update
  app/api/video_stream.py
Labels: fix

#7515 feat: Allow speakers to attain moderation rights in BBB
  app/api/video_stream.py
  app/models/video_stream.py
Labels: feature

#7518 chore: Upgrade flask-rest-jsonapi to support nested sorting
  .circleci/config.yml
  requirements/common.txt
  tests/all/integration/api/test_jsonapi.py
Labels: chore

#7519 chore: Disable sync_backref for viewonly relationship
  app/models/event.py
  app/models/ticket_holder.py
Labels: chore

#7522 feat: Enable Organizer to resend invitation
  app/api/custom/role_invites.py
  app/api/role_invites.py
  app/instance.py
  app/models/role_invite.py
  celerybeat-schedule
Labels: feature

#7525 feat: add is_public field for session fields in custom from
  app/api/schema/custom_forms.py
  app/models/custom_form.py
  migrations/versions/rev-2020-12-20-16:52:09-b0c55c767022_.py
Labels: feature

#7526 chore: Reformat files and remove unused imports
  app/api/custom/role_invites.py
  app/api/event_invoices.py
  app/api/events.py
  app/api/role_invites.py
  app/api/tickets.py
  app/models/role_invite.py
  app/models/ticket.py
Labels: chore

#7529 feat: Allow BCC in session notify API
  app/api/helpers/mail.py
  app/api/schema/sessions.py
  celerybeat-schedule
Labels: feature

#7534 fix: Disable attendee form check if disabled
  app/api/attendees.py
  app/api/helpers/permission_manager.py
  app/api/orders.py
  tests/all/integration/api/attendee/test_attendee_api.py
Labels: fix

#7531 fix: Store current time in mails table
  app/api/helpers/mail.py
Labels: fix

#7535 chore: Upgrade to python 3.8 and marrow mailer fork
  .circleci/config.yml
  .dockerignore
  .env.example
  .gitignore
  .pre-commit-config.yaml
  Dockerfile
  README.md
  app/api/helpers/mail.py
  app/api/schema/sessions.py
  app/instance.py
  docker-compose.yml
  docs/installation/basic.md
  docs/installation/local.md
  pyproject.toml
  requirements/common.txt
  runtime.txt
  setup.cfg
Labels: chore

#7536 chore: Update local.md to fix typo
  docs/installation/local.md
Labels: chore

#7540 fix: sales end should be before event end error message
  app/api/tickets.py
Labels: fix

#7547 fix: discount timezone bug
  app/api/discount_codes.py
Labels: fix

#7541 fix: upgrading custom forms fields is public
  app/models/custom_form.py
  migrations/versions/rev-2020-12-28-11:07:56-7374b18af581_.py
Labels: fix

#7552 fix: Add ticket schema to attendee public schema
  app/api/schema/attendees.py
Labels: fix

#7553 chore: Fix flaky invoice test
  tests/all/integration/api/helpers/test_scheduled_jobs.py
Labels: chore
