Repository fossasia/open-event-server, pull requests merged in 2020-07, with the labels that each got.

#7107 feat: Add speaker custom form logic and validation
  app/api/attendees.py
  app/api/helpers/speaker.py
  app/api/speakers.py
  app/models/custom_form.py
  tests/all/integration/api/speaker/__init__.py
  tests/all/integration/api/speaker/test_speaker_api.py
  tests/factories/speaker.py
  tests/factories/speakers_call.py
Labels: feature

#7108 fix: Make attendee info editable only by admin or that user itself
  app/api/attendees.py
  tests/all/integration/api/attendee/test_attendee_api.py
Labels: fix

#7098 fix: Add proper unique constraints and remove soft deletion from models
  app/api/custom/orders.py
  app/api/event_copy.py
  app/api/helpers/custom_forms.py
  app/api/schema/custom_forms.py
  app/api/schema/event_sub_topics.py
  app/models/custom_form.py
  app/models/discount_code.py
  app/models/event_sub_topic.py
  app/models/role_invite.py
  docs/api/blueprint/custom_forms.apib
  migrations/versions/rev-2020-06-30-20:07:55-f177c14710f1_.py
  migrations/versions/rev-2020-07-03-02:08:01-321c0bf9a52d_.py
Labels: fix

#7115 chore: Prepare for v1.16.0
  CHANGELOG.md
  config.py
Labels: chore

#7112 feat: Add session custom form validations
  app/api/helpers/custom_forms.py
  app/api/schema/sessions.py
  app/api/sessions.py
  app/api/speakers.py
  tests/all/integration/api/helpers/test_pentabarfxml.py
  tests/all/integration/api/session/__init__.py
  tests/all/integration/api/session/test_session_api.py
  tests/factories/session.py
  tests/factories/track.py
Labels: Work in Progress, feature

#7113 fix: Fail order status transition to pending if incomplete attendee info
  app/api/orders.py
  tests/all/integration/api/helpers/order/test_edit_order.py
Labels: fix

#7120 chore: Re-order imports with isort 5
  app/api/helpers/auth.py
  app/api/helpers/order.py
  app/api/orders.py
  autodeploy/main.py
  pyproject.toml
  tests/all/integration/api/helpers/order/test_edit_order.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/all/integration/api/helpers/test_order.py
  tests/all/integration/api/helpers/test_scheduled_jobs.py
  tests/factories/access_code.py
  tests/factories/activities.py
  tests/factories/attendee.py
  tests/factories/custom_placeholder.py
  tests/factories/custom_system_role.py
  tests/factories/discount_code.py
  tests/factories/event.py
  tests/factories/event_copyright.py
  tests/factories/event_invoice.py
  tests/factories/event_location.py
  tests/factories/event_sub_topic.py
  tests/factories/event_topic.py
  tests/factories/event_type.py
  tests/factories/export_job.py
  tests/factories/faq_type.py
  tests/factories/image_size.py
  tests/factories/mail.py
  tests/factories/microlocation.py
  tests/factories/notification.py
  tests/factories/notification_action.py
  tests/factories/page.py
  tests/factories/panel_permission.py
  tests/factories/role.py
  tests/factories/role_invite.py
  tests/factories/service.py
  tests/factories/session.py
  tests/factories/session_type.py
  tests/factories/setting.py
  tests/factories/social_link.py
  tests/factories/speaker.py
  tests/factories/speakers_call.py
  tests/factories/sponsor.py
  tests/factories/stripe_authorization.py
  tests/factories/tax.py
  tests/factories/ticket.py
  tests/factories/ticket_fee.py
  tests/factories/ticket_tag.py
  tests/factories/track.py
  tests/factories/user.py
  tests/factories/user_email.py
  tests/factories/user_permission.py
Labels: chore

#7122 fix: Make user relationship in speaker schema dump_only
  app/api/schema/speakers.py
Labels: fix

#7126 fix: Send after event emails and notifs to unique receivers
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/utilities.py
Labels: fix

#7139 feat: Add option to disable order attachment PDF
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  config.py
Labels: feature

#7143 chore: Change to 'Slides' and 'Comments' in Session Form
  migrations/versions/rev-2020-07-19-08:30:08-8aef207c014f_.py
Labels: chore

#7146 feat: Add cancelled and withdrawn state to session
  app/api/schema/sessions.py
Labels: feature

#7152 fix: Add hack to remove duplicate sessions in user sessions API
  app/api/sessions.py
Labels: fix

#7156 feat: Add session state transition validation
  app/api/helpers/scheduled_jobs.py
  app/api/schema/sessions.py
  app/api/sessions.py
  tests/all/conftest.py
  tests/all/integration/api/session/test_session_forms_api.py
  tests/all/integration/api/session/test_session_state_api.py
Labels: feature

#7157 fix: Send email when change in session state
  app/api/sessions.py
Labels: fix

#7158 fix: remove modules from project
  README.md
  app/api/events.py
  app/api/modules.py
  app/api/routes.py
  app/api/schema/modules.py
  app/models/module.py
  docs/api/api_blueprint_source.apib
  docs/api/blueprint/modules.apib
  manage.py
  migrations/versions/rev-2020-07-24-21:26:41-286869159bb5_.py
  populate_db.py
  tests/factories/module.py
  tests/hook_main.py
Labels: fix

#7162 feat: Add session states API
  app/api/routes.py
  app/api/sessions.py
  app/instance.py
  docs/api/blueprint/session/sessions.apib
  tests/all/integration/api/session/test_session_state_api.py
Labels: feature

#7163 feat: add instagram_url in settings model
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/rev-2020-07-26-08:15:09-507022789bcb_.py
Labels: feature

#7172 fix: Allow organizer to override session form validation
  app/api/schema/sessions.py
  app/api/sessions.py
  tests/all/integration/api/session/test_session_forms_api.py
Labels: fix
