Repository fossasia/open-event-server, pull requests merged in 2020-01, with the labels that each got.

#6707 fix: AWS file upload
  app/api/helpers/storage.py
  tests/all/unit/api/helpers/test_storage.py
Labels: fix

#6714 ref: remove events-orga endpoint
  app/api/event_orga.py
  app/api/routes.py
  app/api/schema/events.py
  app/api/schema/events_orga.py
  app/models/event.py
  migrations/versions/rev-2020-01-03-08:17:26-dee1ad7bee53_.py
Labels: refactor

#6713 ref: remove elasticsearch initialization
  .env.example
  app/instance.py
  kubernetes/deploy.sh
Labels: refactor

#6721 fix: making the created_at dynamic for each order
  app/models/order.py
Labels: fix

#6635 feat: Single endpoint for creating creating an order
  app/api/custom/orders.py
  app/api/helpers/order.py
Labels: feature

#6733 fix: Updated correct celery running command
  docs/installation/basic.md
  docs/installation/local.md
  docs/installation/mac-os.md
  kubernetes/run.sh
  scripts/container_start.sh
  scripts/heroku.sh
  scripts/run.sh
Labels: fix

#6678 fix: Added error handler for status 429
  app/instance.py
Labels: fix

#6737 fix: Introducing Instagram URL in speaker model
  app/api/schema/speakers.py
  app/models/speaker.py
  migrations/versions/rev-2020-01-13-22:43:30-eef7c9bc83a0_.py
Labels: fix

#6739 chore(refactor): Remove versions model file
  app/models/version.py
Labels: chore, refactor

#6740 refactor: dataclass conversion of UserTokenBlackList
  app/api/helpers/auth.py
  app/models/user_token_blacklist.py
Labels: chore, refactor

#6745 feat: Support event statistics in include
  app/api/routes.py
  app/api/schema/events.py
  app/models/event.py
Labels: feature

#6735 feat: Add max_quantity of ticket in order-statistics-event
  app/api/order_statistics/events.py
Labels: feature

#6748 fix: Remove secret from DB and enforce env
  .travis.yml
  app.json
  app/api/helpers/storage.py
  app/api/schema/settings.py
  app/factories/setting.py
  app/instance.py
  app/models/setting.py
  app/settings/__init__.py
  config.py
  docs/api/blueprint/settings.apib
  docs/installation/basic.md
  docs/installation/local.md
  migrations/versions/rev-2020-01-17-01:09:54-30a490ad1609_remove_secret_from_settings.py
  tests/all/integration/setup_database.py
  tests/all/unit/api/helpers/test_storage.py
Labels: fix

#6744 feat: add age_group field in ticket holder model
  app/api/helpers/static.py
  app/api/schema/attendees.py
  app/models/custom_form.py
  app/models/ticket_holder.py
  migrations/versions/rev-2020-01-17-18:09:31-6ebafb385765_.py
Labels: feature

#6754 fix: Removed unrelated change in the migration
  migrations/versions/rev-2020-01-17-18:09:31-6ebafb385765_.py
Labels: fix

#6751 fix: Add appropriate link tags in emails
  app/api/helpers/system_mails.py
Labels: fix

#6755 feat: Addition of is_promoted field in event
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2020-01-18-17:42:13-085a8e2fdfed_.py
Labels: feature

#6757 fix: sessions cannot be edited after cfs ends
  app/api/helpers/speaker.py
  app/api/sessions.py
  app/api/speakers.py
  tests/hook_main.py
Labels: fix

#6759 feat: Replaced jobs running with APS to celery-beat
  app/api/helpers/scheduled_jobs.py
  app/instance.py
Labels: feature

#6752 chore(refactor): Refactor code for custom attendee route
  app/api/attendees.py
  app/api/custom/attendees.py
  app/instance.py
Labels: chore, refactor

#6764 fix: filtered deleted entities from user favourite events
  app/api/user_favourite_events.py
Labels: fix

#6767 fix: Super Admin should be able to delete spam events
  app/api/events.py
Labels: fix

#6771 chore: Prepare for v1.11.0
  CHANGELOG.md
  app/api/server_version.py
Labels: chore

#6770 fix: Ticket query attribute in send event fee
  app/api/helpers/scheduled_jobs.py
Labels: fix

#6468 refactor: Dataclass conversion - Access Codes
  app/factories/access_code.py
  app/models/access_code.py
Labels: chore, refactor

#6777 fix: send event fee notification task triggers on minute
  app/api/helpers/scheduled_jobs.py
Labels: fix

#6778 chore: Prepare for v1.11.1
  CHANGELOG.md
  app/api/server_version.py
Labels: chore

#6779 Merge pull request #6779 from fossasia/master
  CHANGELOG.md
  app/api/helpers/scheduled_jobs.py
  app/api/server_version.py
Labels: chore

#6783 fix: Remaining import of celery instance
  app/api/celery_tasks.py
Labels: fix

#6785 chore: Prepare for v1.11.2
  CHANGELOG.md
  app/api/server_version.py
Labels: chore

#6790 chore: Remove unused imports and variables
  .flake8
  .hound.yml
  .pre-commit-config.yaml
  app/__init__.py
  app/api/admin_statistics_api/mails.py
  app/api/admin_statistics_api/users.py
  app/api/attendees.py
  app/api/data_layers/EventCopyLayer.py
  app/api/event_copy.py
  app/api/faqs.py
  app/api/feedbacks.py
  app/api/helpers/db.py
  app/api/helpers/jwt.py
  app/api/helpers/order.py
  app/api/helpers/permission_manager.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/tasks.py
  app/api/helpers/utilities.py
  app/api/orders.py
  app/api/panel_permissions.py
  app/api/routes.py
  app/api/schema/events.py
  app/api/session_types.py
  app/api/sessions.py
  app/api/settings.py
  app/api/stripe_authorization.py
  app/api/users.py
  app/models/event_topic.py
  tests/all/integration/api/helpers/test_files.py
  tests/all/integration/api/helpers/test_pentabarfxml.py
  tests/all/integration/api/helpers/test_permission_manager.py
  tests/all/integration/api/validation/test_sessions.py
  tests/all/integration/api/validation/test_speakers_call.py
  tests/all/integration/api/validation/test_tickets.py
  tests/all/unit/api/helpers/test_storage.py
Labels: chore

#6789 fix: add check if donation ticket has payment method enabled
  app/api/tickets.py
Labels: fix

#6792 fix: returning duplicated sessions
  app/api/sessions.py
Labels: fix
