Repository fossasia/open-event-server, pull requests merged in 2020-10, with the labels that each got.

#7308 chore: Remove redundant cache delete command
  Dockerfile
Labels: chore

#7312 fix: Correct invoice permissions and disable post, patch, delete
  app/api/event_invoices.py
  docs/api/blueprint/invoices.apib
  tests/all/integration/api/event_invoices/__init__.py
  tests/all/integration/api/event_invoices/test_event_invoices_access.py
Labels: fix

#7313 fix: Make admin billing info public
  app/api/schema/settings.py
Labels: fix

#7314 fix: Invoice identifier and generation behaviour change
  app/api/helpers/scheduled_jobs.py
  app/api/schema/event_invoices.py
  app/models/event_invoice.py
Labels: fix

#7315 fix: Add newline to address in invoice PDF
  app/models/event_invoice.py
  app/models/setting.py
  app/models/user.py
  app/templates/pdf/event_invoice.html
Labels: fix

#7322 fix: Admin Sales API
  app/api/admin_sales/events.py
  app/api/admin_sales/marketer.py
  app/api/admin_sales/organizer.py
  app/api/admin_sales/utils.py
Labels: fix

#7323 chore: Configure pre-commit for excluding files through black
  .pre-commit-config.yaml
Labels: chore

#7325 fix: Allow admin to view all draft events
  app/api/events.py
Labels: fix

#7337 chore: Prepare for v1.18.0
  CHANGELOG.md
  config.py
Labels: chore

#7338 feat: Schedule invoice notifications
  app/api/helpers/scheduled_jobs.py
Labels: feature

#7341 chore: Configure sentry release and increase trace sample rate
  app/instance.py
  config.py
Labels: chore

#7352 chore: Add pyupgrade to pre-commit hooks
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  app/api/orders.py
  requirements/dev.txt
Labels: chore

#7353 fix: Remove session versions table
  app/models/session.py
  migrations/versions/rev-2020-10-13-16:18:06-abad6f635a43_.py
Labels: fix

#7354 chore: Sync migrations of prod and code
  app/models/event.py
  app/models/panel_permission.py
  app/models/session_speaker_link.py
  app/models/speaker.py
  migrations/versions/rev-2020-10-13-17:03:26-d512ae8422a0_.py
Labels: chore

#7356 fix: Correct session link and add site_link property
  app/api/helpers/mail.py
  app/api/sessions.py
  app/models/event.py
  app/models/session.py
  tests/all/integration/models/test_sessions.py
Labels: fix

#7364 fix: Only speaker or organizer can access pending sessions
  .pre-commit-config.yaml
  app/api/helpers/permission_manager.py
  app/api/sessions.py
  tests/all/integration/api/session/test_session_access_api.py
Labels: fix

#7320 chore(docs): Improve local installation guide
  .env.example
  deb-packages.txt
  docs/installation/basic.md
  docs/installation/local.md
  scripts/run.sh
Labels: docs

#7367 fix: add access control check for draft events
  app/api/events.py
  app/models/event.py
  docs/api/blueprint/event/events.apib
  tests/all/integration/api/event/test_event_view_access.py
Labels: fix

#7375 chore: Remove anchor tag from session state change email
  app/api/helpers/system_mails.py
Labels: chore

#7377 feat: Allow order amount override from maintainers
  app/api/custom/orders.py
  app/api/custom/schema/order_amount.py
  tests/all/integration/api/helpers/order/test_create_order.py
Labels: feature

#7376 fix: organizer can add speaker without email
  app/api/schema/speakers.py
  app/api/speakers.py
Labels: fix

#7378 fix: non-organizer user can't set email null
  app/api/speakers.py
Labels: fix

#7381 chore(docs): Correct name of Postgres "peer" authentication method
  docs/installation/local.md
Labels: docs

#7360 feat: Add Video Stream API
  app/api/helpers/files.py
  app/api/microlocations.py
  app/api/routes.py
  app/api/schema/microlocations.py
  app/api/schema/video_stream.py
  app/api/video_stream.py
  app/models/microlocation.py
  app/models/video_stream.py
  app/settings/__init__.py
  migrations/versions/rev-2020-10-15-20:21:34-5e7082330d80_.py
  scripts/lint.sh
  tests/all/integration/api/event/test_event_view_access.py
  tests/all/integration/api/video_stream/__init__.py
  tests/all/integration/api/video_stream/test_video_stream_access_api.py
  tests/all/integration/api/video_stream/test_video_stream_create_api.py
  tests/all/integration/api/video_stream/test_video_stream_edit_api.py
  tests/factories/microlocation.py
  tests/factories/video_stream.py
Labels: feature

#7393 feat: Allow unverified users to buy free tickets
  app/api/orders.py
  app/api/users.py
  config.py
  docs/api/blueprint/user/users.apib
Labels: feature

#7394 fix: Only prevent fulfilled or pending order users from deletion
  app/api/users.py
Labels: fix

#7395 fix: Expand order access to ticket holders
  app/api/attendees.py
  app/api/custom/invoices.py
  app/api/custom/orders.py
  app/api/orders.py
  app/models/order.py
  app/models/user.py
Labels: fix

#7399 fix: Merge welcome and email verification mail
  app/api/helpers/system_mails.py
  app/api/users.py
Labels: fix
