Repository fossasia/open-event-server, pull requests merged in 2020-04, with the labels that each got.

#6909 chore: Use postgis postgres for geolocation based querying
  CHANGELOG.md
  docker-compose.yml
Labels: chore

#6911 fix: correct verification emails for order message
  app/api/custom/orders.py
Labels: fix

#6915 fix: Allow old dates in patch request
  app/api/schema/sessions.py
Labels: fix

#6918 docs(installation): fix typos
  docs/installation/digital-ocean.md
  docs/installation/docker.md
  docs/installation/heroku.md
  docs/installation/local.md
Labels: docs

#6904 chore: Add Helm chart for open event
  charts/Chart.yaml
  charts/README.md
  charts/charts/postgresql-8.6.10.tgz
  charts/charts/redis-10.5.14.tgz
  charts/requirements.lock
  charts/requirements.yaml
  charts/templates/_helpers.tpl
  charts/templates/celery-claim0-persistentvolumeclaim.yaml
  charts/templates/celery-claim1-persistentvolumeclaim.yaml
  charts/templates/celery-deployment.yaml
  charts/templates/frontend-deployment.yaml
  charts/templates/frontend-service.yaml
  charts/templates/ingress.yaml
  charts/templates/web-claim0-persistentvolumeclaim.yaml
  charts/templates/web-claim1-persistentvolumeclaim.yaml
  charts/templates/web-deployment.yaml
  charts/templates/web-service.yaml
  charts/values.yaml
Labels: chore

#6926 chore: Pin dependency versions
  .Pipfile
  .Pipfile.lock
  app/templates/flask_ext/jinja/filters.py
  requirements/common.txt
  requirements/dev.txt
  requirements/tests.txt
Labels: chore

#6925 chore: Update test file pattern in .deepsource.toml
  .deepsource.toml
Labels: chore

#6924 fix: Handle ticket fee not found error in send monthly invoice
  app/api/helpers/scheduled_jobs.py
Labels: fix
