Repository fossasia/open-event-server, pull requests merged in 2020-11, with the labels that each got.

#7389 fix: Restrict event query API
  app/api/access_codes.py
  app/api/attendees.py
  app/api/event_invoices.py
  app/api/events.py
  app/api/helpers/permission_manager.py
  app/api/helpers/query.py
  app/api/orders.py
  app/api/settings.py
  app/api/speakers.py
  app/api/stripe_authorization.py
  app/api/tax.py
  app/api/tickets.py
  app/api/user_favourite_events.py
  tests/all/conftest.py
  tests/all/integration/api/attendee/test_attendee_access_api.py
  tests/all/integration/api/helpers/test_query.py
Labels: fix

#7404 fix: Allow organizer info links
  app/models/event.py
Labels: fix

#7403 fix: Add user_id check before error in event invoice API
  app/api/event_invoices.py
Labels: fix

#7413 feat: Revamp order mails
  app/api/helpers/mail.py
  app/api/helpers/mail_recorder.py
  app/api/helpers/system_mails.py
  app/api/helpers/tasks.py
  app/instance.py
  app/models/event.py
  app/templates/email/ticket_purchased.html
  app/templates/email/ticket_purchased_attendee.html
Labels: feature

#7414 feat: Add direct ICS export URL
  app/api/custom/calendars.py
  app/api/helpers/ICalExporter.py
  app/api/helpers/calendar/ical.py
  app/api/helpers/permissions.py
  app/api/helpers/tasks.py
  app/instance.py
  app/models/event.py
  tests/all/integration/api/helpers/test_icalexporter.py
Labels: feature

#7392 fix: prevent deletion of ticket that has sales
  app/api/tickets.py
  app/models/ticket.py
Labels: fix

#7418 chore(ref): Refactor order complete logic
  app/api/custom/attendees.py
  app/api/custom/invoices.py
  app/api/custom/orders.py
  app/api/helpers/mail.py
  app/api/helpers/notification.py
  app/api/helpers/order.py
  app/api/helpers/system_mails.py
  app/api/helpers/ticketing.py
  app/api/orders.py
  app/models/order.py
  tests/all/integration/api/helpers/test_notification.py
Labels: chore, refactor

#7415 chore(docs): Add comma in storage options docs
  README.md
Labels: docs

#7416 feat: Email made translatable
  .gitignore
  Dockerfile
  app/api/auth.py
  app/api/helpers/system_mails.py
  app/api/users.py
  app/instance.py
  app/templates/email/password_change.html
  app/templates/email/password_reset.html
  app/templates/email/password_reset_and_verify.html
  app/templates/email/ticket_purchased.html
  app/templates/email/ticket_purchased_attendee.html
  app/templates/email/user_register.html
  app/translations/bn/LC_MESSAGES/messages.mo
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.mo
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.mo
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.mo
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.mo
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.mo
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.mo
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.mo
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/pl/LC_MESSAGES/messages.mo
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.mo
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.mo
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.mo
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.mo
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.mo
  app/translations/zh_Hant/LC_MESSAGES/messages.po
  babel.cfg
  config.py
  requirements/common.txt
  scripts/heroku.sh
  scripts/l10n.sh
Labels: feature

#7419 chore: Translations update from Weblate (Norwegian Bokmål)
  app/translations/nb_NO/LC_MESSAGES/messages.po
Labels: chore

#7420 chore: Translated using Weblate (German)
  app/translations/de/LC_MESSAGES/messages.po
Labels: chore

#7425 fix: Filter deleted events from admin sales API
  app/api/admin_sales/events.py
Labels: fix

#7426 fix: Use correct order path while returning PDF
  app/api/custom/invoices.py
  app/api/custom/orders.py
Labels: fix

#7429 fix: Pass email string to send_email, not User
  app/api/auth.py
  app/api/helpers/mail.py
  app/api/users.py
Labels: fix

#7435 fix: make annoucement filed in speakers call nullable
  app/api/schema/speakers_calls.py
  app/models/speakers_call.py
  migrations/versions/rev-2020-11-12-09:02:31-aa9daed401f7_.py
Labels: fix

#7442 fix: Allow none for password and additional info in VideoStream
  app/api/schema/video_stream.py
Labels: fix

#7444 feat: Export custom forms field in csv, pdf for attendee
  app/api/helpers/csv_jobs_util.py
  app/api/helpers/tasks.py
  app/models/custom_form.py
  app/templates/pdf/attendees_pdf.html
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/factories/custom_form.py
Labels: feature

#7240 fix: Remove editing role invites
  app/api/role_invites.py
  docs/api/blueprint/role/role_invites.apib
  tests/hook_main.py
Labels: fix

#7446 chore: Add gevent worker
  Dockerfile
  requirements/common.txt
  scripts/container_start.sh
Labels: chore

#7448 fix: Check non-deleted events before user deletion
  app/api/users.py
Labels: fix

#7447 fix: Show Location, Online Event, Mixed Event or To be Announced info correctly
  app/templates/pdf/ticket_attendee.html
  app/templates/pdf/ticket_purchaser.html
Labels: fix

#7449 fix: Handle orphan video stream access
  app/models/video_stream.py
Labels: fix

#7451 feat: add weblate_url in settings model
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/rev-2020-11-16-15:19:38-74a148c0100d_.py
Labels: feature

#7453 feat: add "withdrawn" and "canceled" speakers and sessions in statistics.
  app/api/schema/event_statistics.py
Labels: feature

#7454 fix: Filter after events efficiently
  app/api/helpers/scheduled_jobs.py
Labels: fix

#7455 fix: required twitter link to show on upcoming event
  app/api/events.py
Labels: fix

#7452 feat: Changed pdf datetime to event timezones
  app/models/event_invoice.py
  app/templates/flask_ext/jinja/filters.py
  app/templates/pdf/attendees_pdf.html
  app/templates/pdf/event_invoice.html
  app/templates/pdf/orders.html
Labels: feature

#7457 feat: Add room position column
  app/api/schema/microlocations.py
  app/models/microlocation.py
  migrations/versions/rev-2020-11-19-22:01:06-5ce97283f4bd_.py
Labels: feature

#7460 fix: Remove ability to delete orders
  app/api/attendees.py
  app/api/helpers/order.py
  app/api/orders.py
  app/api/schema/orders.py
  app/models/discount_code.py
  app/models/order.py
  docs/api/blueprint/order/orders.apib
  migrations/versions/rev-2020-11-21-21:05:50-4642459983c0_.py
Labels: fix

#7458 feat: Separate ticket for each attendee
  app/api/custom/invoices.py
  app/api/custom/orders.py
  app/api/helpers/order.py
  app/api/helpers/storage.py
  app/models/order.py
  app/models/ticket_holder.py
Labels: feature

#7462 feat: Create attendee pdf for every ticket holder
  app/api/helpers/order.py
Labels: feature

#7465 fix: updating condition to not show empty session in user section
  app/api/speakers.py
Labels: fix

#7463 chore: Change tests to circle CI
  .circleci/config.yml
  .travis.yml
Labels: chore

#7466 fix: Add calname to ICS export
  app/api/helpers/calendar/ical.py
Labels: fix

#7468 fix: Change content-type of ICS export
  app/api/custom/calendars.py
Labels: fix

#7471 fix: Filter attendees when ticket holder is not ticket purchaser
  app/api/attendees.py
  app/api/schema/orders.py
  app/models/order.py
Labels: feature

#7472 fix: Do not send invoice if amount < minimum
  app/models/event_invoice.py
Labels: fix

#7478 chore: Prepare for v1.19.0
  CHANGELOG.md
  config.py
Labels: chore
