Repository fossasia/open-event-server, pull requests merged in 2020-02, with the labels that each got.

#6808 chore: Add TicketHolderFactory
  app/factories/ticket_holder.py
Labels: chore

#6810 fix: General Event Statistics type
  app/api/schema/events.py
Labels: fix

#6812 chore: Prepare for v1.12.0
  CHANGELOG.md
  app/api/server_version.py
Labels: chore

#6728 test: Added test for created_at
  app/factories/attendee.py
  app/factories/role_invite.py
  app/factories/session.py
  app/factories/user_token_blacklist.py
  app/models/access_code.py
  app/models/discount_code.py
  app/models/role_invite.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/all/integration/api/helpers/test_scheduled_jobs.py
  tests/all/unit/api/validation/test_createdat.py
Labels: testing

#6804 fix: Invoice emails errors fixed and integration test
  app/api/helpers/scheduled_jobs.py
  app/factories/common.py
  tests/all/integration/api/helpers/test_scheduled_jobs.py
Labels: fix

#6824 chore: Pin werkzeug version
  requirements/common.txt
Labels: chore

#6821 fix: Removed inaccessible link & added user request info
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
Labels: fix

#6825 fix: Use new werkzeug imports
  app/api/helpers/import_helpers.py
Labels: fix

#6831 fix: Error in deleting user with marketer role
  app/api/users.py
Labels: fix

#6839 chore: Add pytype
  .gitignore
  app/api/__init__.py
  app/api/admin_sales/__init__.py
  app/api/attendees.py
  app/api/custom/__init__.py
  app/api/data_layers/__init__.py
  app/api/full_text_search/__init__.py
  app/api/helpers/__init__.py
  app/api/helpers/import_helpers.py
  app/api/helpers/jwt.py
  app/api/helpers/permission_manager.py
  app/api/helpers/tasks.py
  app/api/helpers/third_party_auth.py
  app/api/helpers/ticketing.py
  app/api/helpers/utilities.py
  app/api/order_statistics/__init__.py
  app/api/schema/events.py
  app/extensions/__init__.py
  app/factories/__init__.py
  app/instance.py
  app/models/event.py
  app/models/helpers/__init__.py
  app/models/helpers/versioning.py
  app/models/search/__init__.py
  app/models/track.py
  app/models/user.py
  app/settings/__init__.py
  app/views/__init__.py
  app/views/healthcheck.py
  requirements/dev.txt
  setup.cfg
Labels: chore

#6840 chore: Add pytest CI
  .circleci/config.yml
Labels: chore

#6841 fix: Use circle CI cache properly
  .circleci/config.yml
Labels: fix

#6843 chore: bump flask-admin to 1.5.5
  requirements/common.txt
Labels: chore

#6844 chore: Use weak etags
  requirements/common.txt
Labels: chore

#6850 fix: Cron entries of period tasks
  app/api/helpers/scheduled_jobs.py
Labels: fix

#6854 chore: Prepare for v1.13.0
  CHANGELOG.md
  app/api/server_version.py
Labels: chore

#6853 chore: Release v1.13.0
  .circleci/config.yml
  .gitignore
  CHANGELOG.md
  app/api/__init__.py
  app/api/admin_sales/__init__.py
  app/api/attendees.py
  app/api/custom/__init__.py
  app/api/data_layers/__init__.py
  app/api/full_text_search/__init__.py
  app/api/helpers/__init__.py
  app/api/helpers/import_helpers.py
  app/api/helpers/jwt.py
  app/api/helpers/mail.py
  app/api/helpers/permission_manager.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/system_mails.py
  app/api/helpers/tasks.py
  app/api/helpers/third_party_auth.py
  app/api/helpers/ticketing.py
  app/api/helpers/utilities.py
  app/api/order_statistics/__init__.py
  app/api/schema/events.py
  app/api/server_version.py
  app/api/users.py
  app/extensions/__init__.py
  app/factories/__init__.py
  app/factories/common.py
  app/instance.py
  app/models/event.py
  app/models/helpers/__init__.py
  app/models/helpers/versioning.py
  app/models/search/__init__.py
  app/models/track.py
  app/models/user.py
  app/settings/__init__.py
  app/views/__init__.py
  app/views/healthcheck.py
  requirements/common.txt
  requirements/dev.txt
  setup.cfg
  tests/all/integration/api/helpers/test_scheduled_jobs.py
Labels: chore

#6858 fix: keyerror due to my_tickets_url while rendering tickets template
  app/api/helpers/system_mails.py
Labels: fix

#6859 chore: Prepare for v1.13.1
  CHANGELOG.md
  app/api/server_version.py
Labels: chore

#6860 chore: Release v1.13.1
  CHANGELOG.md
  app/api/helpers/system_mails.py
  app/api/server_version.py
Labels: chore
