Repository fossasia/open-event-server, pull requests merged in 2020-08, with the labels that each got.

#7186 fix: Allow orgnizers to unlock sessions and add tests
  app/api/sessions.py
  tests/all/integration/api/session/test_session_lock_api.py
Labels: fix

#7196 feat: Add session state change emails
  app/api/helpers/mail.py
  app/api/helpers/notification.py
  app/api/helpers/system_mails.py
  app/api/helpers/system_notifications.py
  app/api/helpers/tasks.py
  app/api/schema/message_settings.py
  app/api/sessions.py
  app/models/mail.py
  app/models/message_setting.py
  app/models/notification.py
  migrations/versions/rev-2020-08-08-16:56:27-61bec04ae010_.py
  populate_db.py
  tests/all/integration/api/helpers/test_notification.py
  tests/all/integration/api/helpers/test_systemnotifications.py
Labels: feature

#7197 fix: Add public payment gateway key in settings
  app/api/schema/settings.py
  tests/all/integration/api/test_settings.py
Labels: fix

#7198 feat: Add session mails and notify endpoint
  app/api/helpers/mail.py
  app/api/helpers/permission_manager.py
  app/api/routes.py
  app/api/schema/sessions.py
  app/api/sessions.py
  app/models/helpers/versioning.py
  docs/api/blueprint/session/sessions.apib
Labels: feature

#7203 chore: Prepare v1.17.0
  CHANGELOG.md
  config.py
Labels: chore

#7214 chore(docs): Add steps to configure pre-commit hooks
  docs/installation/local.md
Labels: docs

#7225 fix: Remove soft deletion in roles and role_invites models and schemas
  app/api/schema/role_invites.py
  app/api/schema/roles.py
  app/models/role.py
  app/models/role_invite.py
  migrations/versions/rev-2020-08-25-18:17:01-57a62630eeea_.py
Labels: fix

#7228 feat: Add fields for online events
  app/api/events.py
  app/api/schema/events.py
  app/models/event.py
  docs/api/blueprint/event/events.apib
  migrations/versions/rev-2020-08-27-12:51:55-be959d7b84d4_.py
  migrations/versions/rev-2020-08-27-13:19:10-b8250aa26422_.py
  migrations/versions/rev-2020-08-27-13:26:51-576e8d0170ba_.py
Labels: feature

#7229 fix: Remove location and online checks for event
  app/api/events.py
Labels: fix

#7231 chore(tests): Enable dredd tests for event role permissions API
  app/api/schema/event_role_permissions.py
  tests/hook_main.py
Labels: chore, testing
