Repository fossasia/open-event-server, pull requests merged in 2020-03, with the labels that each got.

#6871 fix: Ticket sold count query
  app/api/attendees.py
  tests/all/integration/api/helpers/test_order.py
Labels: fix

#6877 fix: Ticket sold count query (#6871)
  app/api/attendees.py
  tests/all/integration/api/helpers/test_order.py
Labels: fix

#6878 fix: Discount code quantity calculation
  app/api/helpers/ticketing.py
  app/factories/discount_code.py
  app/models/discount_code.py
  tests/all/integration/api/helpers/test_ticketing.py
Labels: fix

#6881 chore: Prepare for v1.14.0
  CHANGELOG.md
  app/api/server_version.py
Labels: chore

#6887 chore(docs): fix minor typo
  docs/general/api.md
Labels: docs

#6901 chore: Integrate Sentry APM tracing
  app/instance.py
Labels: chore

#6902 feat: Initialize alpha GraphQL support
  app/graphql/schema.py
  app/graphql/types/settings/schema.py
  app/graphql/utils/fields.py
  app/graphql/views.py
  app/instance.py
  requirements/common.txt
  tests/all/unit/graphql/__init__.py
  tests/all/unit/graphql/utils/__init__.py
  tests/all/unit/graphql/utils/test_fields.py
Labels: feature
