Repository fossasia/open-event-server, pull requests merged in 2020-06, with the labels that each got.

#7036 refactor: Use OrderAmountInputSchema
  app/api/custom/orders.py
  app/api/custom/schema/order_amount.py
  app/api/helpers/order.py
Labels: chore, refactor

#7037 fix: Included tax calculation
  app/api/helpers/order.py
  tests/all/integration/api/helpers/order/test_calculate_order_amount.py
Labels: fix

#7047 feat: New Create Order API
  app/api/attendees.py
  app/api/custom/orders.py
  app/api/helpers/order.py
  app/api/orders.py
  app/models/order.py
  app/models/ticket.py
  app/templates/flask_ext/jinja/filters.py
  tests/all/integration/api/helpers/order/test_create_order.py
  tests/all/integration/api/helpers/test_order.py
  tests/factories/order.py
Labels: feature

#7050 feat: Expire initializing attendees automatically
  app/api/helpers/scheduled_jobs.py
  tests/all/integration/api/helpers/test_scheduled_jobs.py
  tests/factories/attendee.py
  tests/factories/event_invoice.py
Labels: feature

#7051 chore: Re-organize imports
  app/api/access_codes.py
  app/api/attendees.py
  app/api/data_layers/EventCopyLayer.py
  app/api/events.py
  app/api/helpers/scheduled_jobs.py
  app/api/server_version.py
  app/api/stripe_authorization.py
  app/api/users.py
  app/graphql/schema.py
  app/graphql/types/settings/schema.py
  app/models/access_code.py
  app/models/export_job.py
  app/models/message_setting.py
  app/models/role_invite.py
  app/models/ticket.py
  app/templates/flask_ext/jinja/filters.py
  autodeploy/auto_updater.py
  scripts/lint.sh
  tests/all/conftest.py
  tests/all/integration/api/helpers/order/test_create_order.py
  tests/all/integration/api/helpers/test_auth.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/all/integration/api/helpers/test_db.py
  tests/all/integration/api/helpers/test_events.py
  tests/all/integration/api/helpers/test_export_helpers.py
  tests/all/integration/api/helpers/test_icalexporter.py
  tests/all/integration/api/helpers/test_jwt.py
  tests/all/integration/api/helpers/test_notification.py
  tests/all/integration/api/helpers/test_pentabarfxml.py
  tests/all/integration/api/helpers/test_xcal.py
  tests/all/integration/api/validation/test_access_codes.py
  tests/all/integration/api/validation/test_sessions.py
  tests/all/integration/api/validation/test_speakers_call.py
  tests/all/integration/api/validation/test_tickets.py
  tests/factories/access_code.py
  tests/factories/attendee.py
  tests/factories/base.py
  tests/factories/custom_form.py
  tests/factories/discount_code.py
  tests/factories/email_notification.py
Labels: chore

#7056 fix: Prevent arbitrary order update
  app/api/orders.py
  app/models/__init__.py
  app/models/order.py
  tests/all/conftest.py
  tests/all/integration/api/helpers/order/test_create_order.py
  tests/all/integration/api/helpers/order/test_edit_order.py
Labels: fix

#7058 fix: Move objproxies import in test branch
  app/models/__init__.py
Labels: fix

#7064 feat: Add name to custom form fields
  app/api/schema/custom_forms.py
  app/models/custom_form.py
  app/models/discount_code.py
  app/models/event_sub_topic.py
  docs/api/blueprint/custom_forms.apib
  migrations/versions/rev-2020-06-20-18:57:43-9540464e9b57_.py
  migrations/versions/rev-2020-06-20-20:02:33-abc8b96ce72c_.py
  tests/all/integration/models/__init__.py
  tests/all/integration/models/custom_form_tests.py
  tests/factories/custom_form.py
  tests/factories/discount_code.py
Labels: feature

#7070 feat: Add validation for required fields in attendee form
  app/api/attendees.py
  app/api/schema/attendees.py
  app/models/custom_form.py
  docs/api/blueprint/attendees.apib
  tests/all/integration/api/attendee/__init__.py
  tests/all/integration/api/attendee/test_attendee_api.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/all/integration/models/test_custom_forms.py
  tests/factories/attendee.py
Labels: feature

#7073 feat: Add complex custom form validations
  app/api/attendees.py
  app/api/helpers/custom_forms.py
  app/models/__init__.py
  tests/all/integration/api/attendee/test_attendee_api.py
Labels: feature

#7078 feat: Normalize custom form fields to snake case
  app/api/helpers/custom_forms.py
  app/api/helpers/fields.py
  app/api/helpers/utilities.py
  app/api/schema/attendees.py
  app/api/schema/sessions.py
  app/api/schema/speakers.py
  app/models/custom_form.py
  tests/all/integration/api/attendee/test_attendee_api.py
  tests/all/unit/api/helpers/test_utilities.py
Labels: feature

#7081 feat: Ignore non-included form fields in complex form
  app/api/attendees.py
  app/api/helpers/custom_forms.py
  tests/all/integration/api/attendee/test_attendee_api.py
Labels: feature

#7082 test: Throw on invalid custom form field and value
  tests/all/integration/api/attendee/test_attendee_api.py
  tests/all/integration/api/validation/test_created_at.py
Labels: testing

#7049 feat: Add endpoint for upcoming events
  app/api/events.py
  app/api/routes.py
  docs/api/blueprint/event/events.apib
  tests/hook_main.py
Labels: feature

#7088 feat: Make event and ticket non-null for attendee
  app/api/custom/orders.py
  app/models/ticket_holder.py
  migrations/versions/rev-2020-06-29-02:39:51-64439b77fa6d_.py
  tests/all/integration/api/custom_forms/test_custom_forms_api.py
  tests/all/integration/api/helpers/order/test_create_order.py
  tests/all/integration/api/helpers/order/test_validate_discount_code.py
  tests/all/integration/api/helpers/test_order.py
  tests/all/integration/api/helpers/test_scheduled_jobs.py
  tests/all/integration/api/helpers/test_ticketing.py
  tests/factories/attendee.py
Labels: feature

#7089 chore: Format files and polish
  app/api/events.py
  app/api/helpers/custom_forms.py
  app/api/routes.py
  autodeploy/auto_updater.py
  tests/all/integration/api/attendee/test_attendee_api.py
Labels: chore

#7090 feat: Make all order relationships read only
  app/api/schema/orders.py
  tests/all/integration/api/helpers/order/test_edit_order.py
Labels: feature

#7085 fix: Disallow attendee editing if order status not initializing
  app/api/attendees.py
  tests/all/integration/api/attendee/test_attendee_api.py
  tests/hook_main.py
Labels: fix

#7096 fix: Make event-invoices endpoint admin only
  app/api/event_invoices.py
  app/api/helpers/permission_manager.py
Labels: fix
