Repository fossasia/open-event-server, pull requests merged in 2021-03, with the labels that each got.

#7788 chore: Make profile public false
  app/api/schema/users.py
  app/models/user.py
Labels: chore

#7789 feat: Add social media bulk tweet generator
  scripts/generate_session_tweet_csv.py
Labels: feature

#7794 feat: Make emails citext
  app/models/discount_code.py
  app/models/speaker.py
  app/models/ticket_holder.py
  app/models/user.py
  app/models/video_stream_moderator.py
  create_db.py
  manage.py
  migrations/versions/rev-2021-03-03-04:05:27-23ccdfcae6a0_make_emails_citext.py
  poetry.lock
  pyproject.toml
  tests/all/conftest.py
  tests/all/integration/setup_database.py
  tests/hook_main.py
Labels: feature

#7795 feat: Youtube and Vimeo: add loop in extras
  app/api/schema/video_stream.py
Labels: feature

#7796 fix: Handle private profile logic correctly
  app/api/helpers/permission_manager.py
  app/api/schema/users.py
Labels: fix

#7799 feat: add "related sessions" in exhibitors
  app/api/exhibitors.py
  app/api/routes.py
  app/api/schema/exhibitors.py
  app/api/schema/sessions.py
  app/api/sessions.py
  app/models/exhibitor.py
  migrations/versions/rev-2021-03-03-04:05:27-23ccdfcae6a0_make_emails_citext.py
  migrations/versions/rev-2021-03-04-04:50:05-8fcb77246ccf_.py
Labels: feature

#7800 fix: Don't show public name if profile is private
  app/api/schema/users.py
  app/api/video_stream.py
Labels: fix

#7805 feat: Add API to delete unused discount codes
  app/api/custom/events.py
Labels: feature

#7806 feat: Add more fields in session export CSV
  app/api/helpers/csv_jobs_util.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
Labels: feature

#7807 feat: Use random names instead of Anonymous User
  app/api/schema/users.py
  app/api/video_stream.py
  app/models/user.py
  poetry.lock
  pyproject.toml
Labels: feature

#7808 fix: Move user private profile check to session fav
  app/api/schema/user_favourite_sessions.py
  app/api/schema/users.py
  app/models/user_favourite_session.py
Labels: fix

#7766 feat: Add link to online room in location field of session calendar.
  app/api/helpers/calendar/ical.py
  tests/all/integration/api/helpers/test_icalexporter.py
Labels: feature

#7811 feat: Integrate Rocket Chat
  app/api/chat/__init__.py
  app/api/chat/rocket_chat.py
  app/api/helpers/utilities.py
  app/api/schema/settings.py
  app/api/video_stream.py
  app/models/setting.py
  app/models/user.py
  app/models/user_favourite_session.py
  migrations/versions/rev-2021-03-09-10:07:46-5900f4433257_add_rocket_chat.py
  migrations/versions/rev-2021-03-09-10:35:32-92e0289733a0_add_rocket_chat_token.py
Labels: feature

#7815 fix: Make chat token fetching more robust
  app/api/chat/rocket_chat.py
  app/api/video_stream.py
Labels: fix

#7816 feat: Properly slugify rocket chat username
  app/models/user.py
  poetry.lock
  pyproject.toml
Labels: feature

#7818 feat: Add mastadon option to Session, Speaker and Custom Forms
  app/api/schema/sessions.py
  app/api/schema/speakers.py
  app/models/custom_form.py
  app/models/session.py
  app/models/speaker.py
  migrations/versions/rev-2021-03-10-19:23:44-6c79ac9607e7_.py
Labels: feature

#7822 feat: Add random identifier to rc username on conflict
  app/api/chat/rocket_chat.py
  app/api/helpers/db.py
Labels: feature

#7823 fix: Remove autoescape from after order message in email
  app/templates/email/ticket_purchased.html
  app/templates/email/ticket_purchased_attendee.html
Labels: fix

#7824 fix: change session-ical to event-ical in Ticket Order Email
  app/api/helpers/ICalExporter.py
  app/api/helpers/files.py
  app/api/helpers/mail.py
Labels: fix

#7828 chore: Add is rocket chat registered on user model
  app/api/schema/users.py
  app/models/user.py
Labels: chore

#7812 fix: remove moderator access from speakers
  app/models/video_stream.py
Labels: fix

#7829 feat: Enable BBB recording
  app/api/video_stream.py
Labels: feature

#7831 fix: Sessions & Speaker: rename column mastadon -> mastodon
  app/api/schema/sessions.py
  app/api/schema/speakers.py
  app/models/custom_form.py
  app/models/session.py
  app/models/speaker.py
  migrations/versions/rev-2021-03-15-21:31:47-681bb276443e_.py
Labels: fix

#7834 fix: Throw error on duplicate discount code
  app/api/discount_codes.py
  app/api/schema/discount_codes.py
Labels: fix

#7843 fix: Permission check in ticket discount codes access
  app/api/discount_codes.py
Labels: fix

#7838 feat: BBB getRecording endpoint
  app/api/video_stream.py
Labels: feature

#7848 feat: Allow chat toggle
  app/api/events.py
  app/api/schema/events.py
  app/api/video_stream.py
  app/models/event.py
  migrations/versions/rev-2021-03-24-03:08:23-c32364a17072_.py
Labels: feature

#7835 feat: add record, autoStartMeeting, muteOnStart parameters to bbb
  app/api/schema/video_stream.py
  app/api/video_stream.py
  app/models/video_stream.py
Labels: feature

#7851 feat: Add more bbb options
  app/api/schema/video_stream.py
  app/api/video_channels/bbb.py
Labels: feature
