Repository fossasia/open-event-server, pull requests merged in 2021-08, with the labels that each got.

#7432 fix: link installation steps
  docs/installation/docker.md
Labels: fix

#8081 feat: multiple speaker documents for sessions
  app/api/schema/sessions.py
  app/models/custom_form.py
  app/models/session.py
  migrations/versions/rev-2021-07-22-00:49:24-ab0e4baaabab_.py
  scripts/session_slides_type_to_json.py
Labels: feature, has-migration

#8145 chore: add script file in global struct to import app instance
  session_slides_type_to_json.py
Labels: chore

#8120 feat: Implement "Announce Event" email for group followers
  app/api/custom/groups.py
  app/api/events.py
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/schema/events.py
  app/models/event.py
  app/models/group.py
  app/templates/email/announce_event.html
  migrations/versions/rev-2021-07-21-19:22:46-78f3c24b41cf_.py
Labels: feature, needs-review, has-migration

#8158 fix: don't send invoice reminder if status is paid or resolved
  app/api/helpers/scheduled_jobs.py
Labels: fix

#8118 feat: Admin Sales Page export table as CSV
  app/api/admin_sales/events.py
  app/api/admin_sales/utils.py
  app/api/exports.py
  app/api/helpers/csv_jobs_util.py
  app/api/helpers/tasks.py
Labels: feature

#8167 feat: implement check for follower
  app/api/user_follow_groups.py
Labels: feature

#8163 feat: followers table export as csv
  app/api/exports.py
  app/api/helpers/csv_jobs_util.py
  app/api/helpers/group_user_role.py
  app/api/helpers/tasks.py
Labels: feature

#8168 fix: Prevent groups api from not sending all invites.
  app/api/users_groups_roles.py
Labels: fix

#8172 fix: Fix and improve confirmation email for ticket orders
  app/api/helpers/system_mails.py
  app/models/event.py
  app/templates/email/ticket_purchased.html
Labels: fix

#8165 fix: formatting issues in order invoice
  app/templates/pdf/order_invoice.html
Labels: fix

#8089 feat: reminder for end of ticket sales
  app/api/helpers/mail.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/system_mails.py
  app/templates/email/ticket_sales_end.html
  app/templates/email/ticket_sales_end_next_week.html
  app/templates/email/ticket_sales_end_tomorrow.html
Labels: feature, needs-review

#8164 fix: send announcement email by looping all emails of followers
  app/api/helpers/mail.py
  app/models/group.py
Labels: fix

#8142 feat: apply sorting by amount by sales in admin.sales page
  app/api/admin_sales/events.py
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2021-08-09-10:27:38-528e99098827_.py
Labels: feature, has-migration
