Repository fossasia/open-event-server, pull requests merged in 2021-02, with the labels that each got.

#7693 fix: without session speakers filter
  app/api/schema/event_statistics.py
Labels: fix

#7699 fix: Add timestamp columns in speakers table
  app/models/speaker.py
  migrations/versions/rev-2021-02-02-10:56:23-b75a8dd29262_add_speaker_timestamps.py
Labels: fix

#7700 fix: Limit speaker.gender to limited choices
  app/api/helpers/static.py
  app/api/schema/speakers.py
Labels: fix

#7702 feat: Add speaker reorder API
  app/api/custom/events.py
  app/api/helpers/utilities.py
  app/api/schema/speakers.py
Labels: feature

#7703 feat: Add average_rating column in session
  app/models/session.py
  migrations/versions/rev-2021-02-03-14:52:46-8601d512262a_add_session_average_rating_aggregated_.py
Labels: feature

#7706 feat: Add exhibitor social links
  app/api/schema/exhibitors.py
  app/models/exhibitor.py
  migrations/versions/rev-2021-02-03-17:36:38-d0ac0e357cd9_add_exhibitor_social_links.py
Labels: feature

#7708 feat: Add unique constraint to speaker email
  app/api/helpers/permission_manager.py
  app/api/speakers.py
  app/models/speaker.py
  migrations/versions/rev-2021-02-04-08:50:06-64021ad8ea0e_make_speaker_email_unique.py
  tests/all/integration/api/speaker/test_speaker_api.py
  tests/all/integration/api/speaker/test_speaker_email_override.py
Labels: feature

#7709 fix: Exhibitor social link schema
  app/api/schema/exhibitors.py
Labels: fix

#7711 feat: Enhance cfs mail
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/sessions.py
  app/models/event.py
  app/models/session.py
  app/models/speaker.py
Labels: feature

#7698 fix: allow session state change
  app/api/sessions.py
  tests/all/integration/api/session/test_session_state_api.py
Labels: fix

#7712 feat: Add rating_count to session
  app/api/schema/sessions.py
  app/models/session.py
  migrations/versions/rev-2021-02-05-19:56:46-16d8d69a64e4_add_session_rating_count.py
Labels: feature

#7715 feat: Add exhibitor status
  app/api/schema/exhibitors.py
  app/models/exhibitor.py
  migrations/versions/rev-2021-02-06-09:11:34-a00006a65bff_add_exhibitor_status.py
Labels: feature

#7716 chore: Add index on session state speaker event
  app/models/session.py
  app/models/speaker.py
  migrations/versions/rev-2021-02-06-12:22:08-0aab8f7d6797_add_session_state_speaker_event_index.py
Labels: chore

#7710 chore: add api docs and dredd tests for group
  docs/api/api_blueprint_source.apib
  docs/api/blueprint/event/events.apib
  docs/api/blueprint/groups.apib
  docs/api/blueprint/user/users.apib
  tests/factories/event.py
  tests/hook_main.py
Labels: chore

#7717 feat: Session form: add social link columns
  app/api/schema/sessions.py
  app/models/custom_form.py
  app/models/session.py
  migrations/versions/rev-2021-02-08-01:18:28-6b9d98ec9046_.py
Labels: feature

#7718 fix: Allow null in exhibitor social link
  app/api/schema/exhibitors.py
Labels: fix

#7724 fix: Allow event identifier for session dates
  app/api/custom/events.py
  tests/all/integration/api/event/test_event_session_distinct_dates.py
Labels: fix

#7725 feat: text improvements cfs mail
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/sessions.py
  app/models/event.py
  app/models/session.py
Labels: feature

#7714 feat: Add "Reply-to" to organizers in session notify
  app/api/helpers/mail.py
Labels: feature

#7723 fix: User Favourite Session API
  app/api/routes.py
  app/api/schema/user_favourite_sessions.py
  app/api/user_favourite_sessions.py
  app/models/user.py
  app/models/user_favourite_session.py
Labels: fix

#7728 fix: Add user favourite relationship in session
  app/api/schema/sessions.py
  app/api/schema/user_favourite_sessions.py
  app/api/schema/users.py
  app/models/session.py
Labels: fix

#7729 feat: adding Youtube and vimeo migrations
  migrations/versions/rev-2021-02-10-18:44:50-157df65ec235_.py
  populate_db.py
Labels: feature

#7730 chore: Remove soft deletion from event roles
  app/api/event_copy.py
  app/api/events.py
  app/api/role_invites.py
  app/api/schema/users_events_roles.py
  app/api/users_events_roles.py
  app/models/event.py
  app/models/user.py
  app/models/users_events_role.py
  docs/api/blueprint/role/users_events_roles.apib
  migrations/versions/rev-2021-02-10-21:53:53-aa0585904661_remove_event_role_soft_deletion.py
Labels: chore

#7734 chore: Fix DB head
  migrations/versions/rev-2021-02-10-21:53:53-aa0585904661_remove_event_role_soft_deletion.py
Labels: chore

#7735 feat: add organizers in bcc of session notify mail
  app/api/helpers/mail.py
Labels: feature

#7704 feat: video stream moderator
  app/api/routes.py
  app/api/schema/video_stream.py
  app/api/schema/video_stream_moderators.py
  app/api/video_stream_moderators.py
  app/models/video_stream_moderator.py
  migrations/versions/rev-2021-02-11-14:41:55-b2ba7a0ea5c1_.py
Labels: feature

#7736 feat: Exhibitor: Add Contact Info column
  app/api/schema/exhibitors.py
  app/models/exhibitor.py
  docs/api/blueprint/exhibitors.apib
  migrations/versions/rev-2021-02-11-22:30:21-9756adf77900_.py
Labels: feature

#7740 fix: Change reply to email to single email
  app/api/helpers/mail.py
Labels: fix

#7742 fix: adding type paragraph
  app/api/helpers/custom_forms.py
  app/api/schema/custom_forms.py
  docs/api/blueprint/custom_forms.apib
Labels: fix

#7731 feat: Organizer Msg: Add Sanitization
  app/models/event.py
Labels: feature

#7744 fix: Check email in bcc before remove
  app/api/helpers/mail.py
Labels: fix

#7745 feat: Exhibitor: add contact-link column & rename contact column
  app/api/schema/exhibitors.py
  app/models/exhibitor.py
  docs/api/blueprint/exhibitors.apib
  migrations/versions/rev-2021-02-14-17:54:18-6f68fb58f228_.py
Labels: feature

#7748 feat: reorder exhibitors
  app/api/custom/events.py
  app/api/helpers/permissions.py
  app/api/schema/exhibitors.py
Labels: feature

#7750 fix: Allow session and speaker update after CfS end
  app/api/helpers/speaker.py
  app/api/sessions.py
  app/api/speakers.py
Labels: fix

#7751 feat: Exhibitor: add is_custom field in Social Links
  app/api/schema/exhibitors.py
Labels: feature

#7753 feat: Exhibitor: Add enable video column
  app/api/schema/exhibitors.py
  app/models/exhibitor.py
  migrations/versions/rev-2021-02-17-13:01:05-b261c9007716_.py
Labels: feature

#7756 feat: Add my schedule sessions in calendar export
  app/api/custom/calendars.py
  app/api/helpers/calendar/ical.py
Labels: feature

#7757 feat: Correct Video Stream Moderator API
  app/api/routes.py
  app/api/schema/video_stream.py
  app/api/schema/video_stream_moderators.py
  app/api/users.py
  app/api/video_stream.py
  app/api/video_stream_moderators.py
  app/models/video_stream_moderator.py
  migrations/versions/rev-2021-02-18-10:52:23-0efe87a56e46_moderator_user_email.py
Labels: feature

#7760 feat: Provide Moderator controls to stream moderators.
  app/models/video_stream.py
Labels: feature

#7761 fix: Ignore session microlocation from speaker instead of error
  app/api/schema/sessions.py
Labels: fix

#7762 fix: Show speaker sessions in user API by email
  app/api/sessions.py
Labels: fix

#7759 feat: Use user_id query for exporting my schedule ICS
  app/api/custom/calendars.py
  app/api/helpers/calendar/ical.py
Labels: feature

#7763 fix: Allow accepted speakers to be moderators as well
  app/api/sessions.py
  app/models/session.py
  app/models/video_stream.py
Labels: fix

#7765 fix: Handle bbb join for users with no name
  app/api/video_stream.py
Labels: fix

#7764 fix: adding image resize for exhibitor banner
  app/api/exhibitors.py
  app/api/helpers/tasks.py
  app/api/helpers/utilities.py
  app/api/schema/exhibitors.py
  app/models/exhibitor.py
  docs/api/blueprint/exhibitors.apib
  manage.py
  migrations/versions/rev-2021-02-20-18:40:40-d92b04bfc2eb_.py
Labels: fix

#7768 fix: Upload exhibitor images to separate folder
  app/api/helpers/files.py
  app/api/helpers/tasks.py
Labels: fix

#7773 feat: Add public name and profile in user
  app/api/schema/users.py
  app/api/video_stream.py
  app/models/user.py
  migrations/versions/rev-2021-02-23-02:48:07-26f3611683b9_user_add_public_profile_and_name.py
Labels: feature

#7774 feat: Make user fav session API user privacy aware
  app/api/schema/users.py
  app/api/user_favourite_sessions.py
Labels: feature

#7778 feat: Add event favourite sessions
  app/api/schema/events.py
  app/api/user_favourite_sessions.py
Labels: feature

#7780 fix: Correct precision of event invoice amount
  .gitignore
  app/models/event_invoice.py
Labels: fix

#7783 feat: Add favourite_count to session
  app/api/schema/sessions.py
  app/models/session.py
  migrations/versions/rev-2021-02-28-20:37:56-cbe8314bce5e_.py
Labels: feature

#7784 feat: Add basic support for websockets
  app/asgi.py
  poetry.lock
  pyproject.toml
Labels: feature

#7785 fix: exhibitor/event API
  app/api/events.py
Labels: fix

#7775 fix: add autoplay for youtube and vimeo
  app/api/schema/video_stream.py
  app/api/video_stream.py
Labels: fix
