Repository fossasia/open-event-server, pull requests merged in 2021-11, with the labels that each got.

#8339 chore: add app_name to after event template
  app/api/helpers/mail.py
  app/templates/email/after_event.html
  app/templates/email/new_session.html
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/hr/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: chore

#8343 fix: failing order due to syntax error in ticket purchaser templates
  app/templates/pdf/ticket_purchaser.html
Labels: fix

#8344 fix: Variable issue in ticker_purchaser template
  app/templates/pdf/ticket_purchaser.html
  poetry.lock
  pyproject.toml
Labels: fix

#8350 fix: html code in emails
  app/templates/email/announce_event.html
  app/templates/email/event_role.html
  app/templates/email/group_role.html
  app/templates/email/monthly_payment_email.html
  app/templates/email/monthly_payment_followup_email.html
  app/templates/email/monthly_payment_post_due_email.html
  app/templates/email/monthly_payment_pre_due_email.html
  app/templates/email/new_session.html
  app/templates/email/speaker_invite.html
  app/templates/email/ticket_cancelled.html
  app/templates/email/ticket_purchased.html
  app/templates/email/ticket_purchased_attendee.html
  app/templates/email/ticket_purchased_organizer.html
  app/templates/email/ticket_sales_end.html
  app/templates/email/ticket_sales_end_next_week.html
  app/templates/email/ticket_sales_end_tomorrow.html
  app/templates/email/user_confirm.html
  app/templates/email/user_event_role.html
  app/templates/email/user_register.html
  app/templates/pdf/ticket_attendee.html
  app/templates/pdf/ticket_purchaser.html
Labels: fix

#8352 chore: make payment status and mode in emails translatable
  app/templates/email/ticket_purchased_organizer.html
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/hr/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: chore

#8355 fix: adding json for position for sorting
  app/api/schema/speakers.py
  app/models/speaker.py
  migrations/versions/rev-2021-11-06-20:56:17-b3cf88a46150_.py
Labels: fix

#8357 chore: pending strings for translation
  app/models/event.py
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/hr/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: chore

#8360 fix: Precommit file for Project
  .pre-commit-config.yaml
Labels: fix

#8359 feat: add to calendar links in ticket purchaser mail
  app/templates/email/ticket_purchased.html
Labels: feature

#8319 feat: Upgraded stripe to latest version
  app/api/custom/orders.py
  app/api/data_layers/ChargesLayer.py
  app/api/helpers/payment.py
  app/api/helpers/ticketing.py
  app/api/orders.py
  app/instance.py
  app/models/order.py
  migrations/versions/rev-2021-11-09-20:38:00-d0b8204bb208_.py
Labels: feature

#8368 fix: Added customer email as prefilled in stripe checkout
  app/api/helpers/payment.py
Labels: fix

#8369 fix: removed unwanted html from ticket purchased mail
  app/templates/email/ticket_purchased.html
Labels: fix

#8373 fix: subjects of mails made translatable
  app/api/helpers/system_mails.py
  app/templates/email/ticket_purchased_organizer.html
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/hr/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/te/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: fix

#8380 chore: fix app_name in subjects of mails
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/hr/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/te/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: chore

#8384 fix: links in sessions mail abstract
  app/templates/email/new_session.html
Labels: fix

#8379 fix: stream.extra not none in BBB video recordings
  app/api/video_recordings.py
Labels: fix

#8415 fix: errors due to wrong logic in donation tickets
  app/api/custom/orders.py
  app/api/helpers/order.py
  app/models/order.py
  migrations/versions/rev-2021-11-22-14:44:00-c4fc87788cd5_.py
Labels: fix

#8412 chore: Fix Ticket Purchased Email template
  app/templates/email/ticket_purchased.html
Labels: chore

#8421 fix: add manager command for group image resize task
  manage.py
Labels: fix

#8371 feat: translate date and time according to user language preference in mails & invoice
  app/api/helpers/mail.py
  app/api/helpers/order.py
  app/templates/email/ticket_purchased.html
  app/templates/email/ticket_purchased_attendee.html
  app/templates/email/ticket_purchased_organizer.html
  app/templates/pdf/ticket_attendee.html
  app/templates/pdf/ticket_purchaser.html
Labels: feature
