Repository fossasia/open-event-server, pull requests merged in 2021-04, with the labels that each got.

#7861 fix: raise conflict on duplicate role invite
  app/api/role_invites.py
Labels: fix

#7862 fix: encode session link in ical
  app/api/helpers/calendar/ical.py
Labels: fix

#7863 chore: Order Invoice made translatable
  app/templates/pdf/order_invoice.html
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: chore

#7869 fix: return empty array from dates endpoint when no session in scheduled.
  app/api/custom/events.py
Labels: fix

#7871 fix: only allow event owners to add event to group
  app/api/groups.py
Labels: fix

#7864 fix: convert email message to html file and remove unwanted emails
  app/api/helpers/mail.py
  app/api/helpers/scheduled_jobs.py
  app/api/helpers/system_mails.py
  app/api/schema/message_settings.py
  app/models/mail.py
  app/models/message_setting.py
  app/models/role_invite.py
  app/templates/email/event_export_fail.html
  app/templates/email/event_exported.html
  app/templates/email/event_import_fail.html
  app/templates/email/event_imported.html
  app/templates/email/event_role.html
  app/templates/email/monthly_payment_email.html
  app/templates/email/monthly_payment_followup_email.html
  app/templates/email/monthly_payment_post_due_email.html
  app/templates/email/monthly_payment_pre_due_email.html
  app/templates/email/new_session.html
  app/templates/email/password_reset.html
  app/templates/email/password_reset_and_verify.html
  app/templates/email/ticket_cancelled.html
  app/templates/email/ticket_purchased.html
  app/templates/email/ticket_purchased_attendee.html
  app/templates/email/ticket_purchased_organizer.html
  app/templates/email/user_change_email.html
  app/templates/email/user_confirm.html
  app/templates/email/user_event_role.html
  app/templates/email/user_register.html
  docs/api/blueprint/message_settings.apib
  populate_db.py
  tests/all/integration/api/group/test_group_misc.py
  tests/all/integration/api/helpers/test_notification.py
  tests/factories/message_setting.py
Labels: fix

#7877 fix: Removed group associated with event when ownership transfer
  app/api/role_invites.py
Labels: fix

#7875 fix: remove extra space in front of colons
  app/templates/email/ticket_purchased.html
  app/templates/pdf/attendees_pdf.html
  app/templates/pdf/orders.html
  create_db.py
Labels: fix

#7876 fix: adding API for User Groups Roles
  app/api/routes.py
  app/api/schema/users_groups_roles.py
  app/api/users_groups_roles.py
  app/models/users_groups_role.py
  migrations/versions/rev-2021-04-07-22:44:01-547aa98b0c41_.py
Labels: fix

#7853 feat: Create private chat room per event
  app/api/chat/rocket_chat.py
  app/api/events.py
  app/api/schema/events.py
  app/api/video_stream.py
  app/models/event.py
  migrations/versions/rev-2021-03-26-02:13:43-49994f8ad895_.py
Labels: feature

#7878 fix: Remove duplicate route for group roles
  app/api/routes.py
Labels: fix

#7879 fix: Check bbb params before iterating
  app/api/video_channels/bbb.py
Labels: fix

#7881 feat: Restructure email settings
  app/api/auth.py
  app/api/custom/events.py
  app/api/helpers/mail.py
  app/api/helpers/notification.py
  app/api/helpers/system_mails.py
  app/api/schema/message_settings.py
  app/api/sessions.py
  app/api/users.py
  app/models/mail.py
  app/models/message_setting.py
  docs/api/blueprint/message_settings.apib
  migrations/versions/rev-2021-04-10-01:03:57-28de2911c790_message_settings_restructure.py
  populate_db.py
  tests/factories/message_setting.py
Labels: feature

#7880 fix: group/events API raises 404 if group is deleted
  app/api/events.py
Labels: fix

#7860 feat: Restructure notifications
  app/api/auth.py
  app/api/helpers/mail.py
  app/api/helpers/notification.py
  app/api/helpers/order.py
  app/api/helpers/system_notifications.py
  app/api/helpers/tasks.py
  app/api/notification_settings.py
  app/api/notifications.py
  app/api/orders.py
  app/api/routes.py
  app/api/schema/notification_settings.py
  app/api/schema/notifications.py
  app/api/sessions.py
  app/api/users.py
  app/models/event.py
  app/models/event_invoice.py
  app/models/notification.py
  app/models/notification_setting.py
  app/models/role_invite.py
  app/models/session.py
  docs/api/blueprint/notification/notifications.apib
  migrations/versions/rev-2021-04-10-19:57:27-a02007782ba2_restructure_notification_model.py
  migrations/versions/rev-2021-04-13-15:57:10-2539c7da2bad_remove_notification_actions.py
  migrations/versions/rev-2021-04-13-18:14:02-a370f2a07c8d_add_notification_settings.py
  populate_db.py
  tests/all/integration/api/helpers/test_notification.py
  tests/all/integration/api/helpers/test_systemnotifications.py
  tests/factories/notification.py
  tests/factories/notification_action.py
  tests/hook_main.py
Labels: feature

#7883 feat: Send email while adding moderator in video room
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/video_stream_moderators.py
  app/templates/email/video_stream_moderator.html
Labels: feature

#7893 chore: Update flask-rest-jsonapi to 0.12.6.5
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: chore

#7885 feat: Add group role invite feature
  app/api/custom/users_groups_roles.py
  app/api/groups.py
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/roles.py
  app/api/routes.py
  app/api/schema/notifications.py
  app/api/schema/users_groups_roles.py
  app/api/users_groups_roles.py
  app/instance.py
  app/models/users_groups_role.py
  app/templates/email/group_role.html
  migrations/versions/rev-2021-04-13-01:29:56-a9266ead39d4_.py
  migrations/versions/rev-2021-04-14-22:32:33-60961e128f46_.py
  tests/all/integration/api/group/test_group_roles.py
  tests/factories/group.py
Labels: feature

#7895 feat: Added 3cx in Video Channel
  migrations/versions/rev-2021-04-15-22:22:02-01f7a9531f83_.py
  populate_db.py
Labels: feature

#7896 chore: Downgrade cryptography
  poetry.lock
  pyproject.toml
Labels: chore

#7890 feat: Added check of group role in is_organizer
  app/models/user.py
  tests/all/integration/api/group/test_group_roles.py
Labels: feature

#7898 fix: Set channel id none for custom rooms
  app/api/video_stream.py
Labels: fix

#7900 chore: include more gender fields in server code
  app/api/helpers/static.py
Labels: chore

#7903 fix: change schema in video_channel api
  app/api/routes.py
  app/api/video_channel.py
Labels: fix

#7894 fix: Require jwt for accepting group role invite
  app/api/custom/users_groups_roles.py
  app/api/schema/groups.py
  app/api/schema/users_groups_roles.py
  app/models/group.py
  app/models/users_groups_role.py
  tests/all/integration/api/group/test_group_roles.py
Labels: fix

#7904 fix: rename chat group name if event renamed
  app/api/chat/rocket_chat.py
  app/api/events.py
  app/api/helpers/tasks.py
Labels: fix

#7911 fix: Add email trim validation in schema
  app/api/helpers/custom_forms.py
  app/api/schema/attendees.py
  app/api/schema/base.py
  app/api/schema/events.py
  app/api/schema/exhibitors.py
  app/api/schema/mails.py
  app/api/schema/role_invites.py
  app/api/schema/settings.py
  app/api/schema/speakers.py
  app/api/schema/user_email.py
  app/api/schema/users.py
  app/api/schema/users_groups_roles.py
  app/api/schema/video_stream_moderators.py
  tests/all/integration/api/event/test_event_roles.py
Labels: fix

#7910 feat: Add GroupFollower model
  app/models/group_follower.py
  migrations/versions/rev-2021-04-22-23:16:58-f19f66ce1467_.py
Labels: feature

#7913 fix: Remove stripe auth soft delete
  app/api/schema/stripe_authorization.py
  app/api/stripe_authorization.py
  app/models/stripe_authorization.py
  docs/api/blueprint/stripe_authorization.apib
  migrations/versions/rev-2021-04-23-16:04:02-51ad369b558b_remove_stripe_authorization_soft_delete.py
Labels: fix
