Repository fossasia/open-event-server, pull requests merged in 2021-07, with the labels that each got.

#8070 feat: video recording delete option for admin
  app/api/video_recordings.py
Labels: feature

#8067 fix: Event Transfer: Current owner to be downgraded to Organiser, no duplicate owner role invites allowed
  app/api/helpers/role_invite.py
  app/api/role_invites.py
Labels: fix

#8084 feat: add social links for groups
  app/api/schema/groups.py
  app/models/group.py
  migrations/versions/rev-2021-07-07-03:47:53-eecca008e169_.py
Labels: feature

#8085 fix: remove class name conflict for socialLinkSchema in group model
  app/api/schema/groups.py
Labels: fix

#8092 feat: add size fields in scehma
  app/api/schema/settings.py
  app/models/setting.py
  migrations/versions/rev-2021-07-09-12:37:01-605687849d3c_.py
Labels: feature, has-migration

#7979 feat: Ask user to end current BBB running meeting after updating video stream
  app/api/schema/video_stream.py
  app/api/video_stream.py
Labels: feature

#8088 feat: added fields ( about, logo, group photo) in group model
  app/api/schema/groups.py
  app/models/group.py
  migrations/versions/rev-2021-07-08-17:33:10-a8d58b96b916_.py
Labels: feature, has-migration

#8037 feat: invite speaker
  app/api/events.py
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/routes.py
  app/api/schema/events.py
  app/api/schema/sessions.py
  app/api/schema/speaker_invites.py
  app/api/sessions.py
  app/api/speaker_invites.py
  app/api/speakers.py
  app/instance.py
  app/models/speaker_invite.py
  app/templates/email/speaker_invite.html
  migrations/versions/rev-2021-07-06-16:37:50-54f963bee31a_.py
Labels: has-migration

#8076 fix: adding is one click signup enabled
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2021-07-04-18:58:12-e73500f7f7d9_.py
Labels: fix, has-migration

#8094 feat: Groups box on admin start page
  app/api/admin_statistics_api/groups.py
  app/api/routes.py
Labels: feature

#8097 fix: simplifying admin sales page
  app/api/admin_sales/events.py
Labels: fix

#8103 fix: remove live-stream and webinar option from event wizard
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2021-07-15-17:10:54-f0ec7ba33589_.py
Labels: fix

#8102 feat: update payment status from admin panel
  app/api/event_invoices.py
  app/api/schema/event_invoices.py
  tests/all/integration/api/event_invoices/test_event_invoices_access.py
Labels: feature

#8111 feat: add group contact columns
  app/api/schema/groups.py
  app/models/group.py
  migrations/versions/rev-2021-07-19-20:40:32-304e8820c95a_.py
Labels: feature

#8116 feat: Add group contact end point
  app/api/custom/groups.py
  app/api/helpers/system_mails.py
  app/api/schema/users_groups_roles.py
  app/instance.py
  app/templates/email/group_contact_user.html
Labels: feature

#8123 chore: remove group contact columns
  app/api/schema/groups.py
  app/models/group.py
  migrations/versions/rev-2021-07-23-18:44:39-9c2b56ad8edb_.py
Labels: chore

#8100 feat: add is_cfs_enabled field in event model
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2021-07-14-19:02:29-7ddfc1ae036c_.py
Labels: feature, has-migration

#8128 fix: add created_at field in follower schema
  app/api/schema/user_follow_groups.py
Labels: fix

#8108 feat: enhance email of speaker invite
  app/api/helpers/mail.py
  app/models/speaker_invite.py
  app/templates/email/speaker_invite.html
Labels: feature, needs-review

#8101 fix: Invoice Organisation and Reverse Charge info missing
  app/templates/pdf/event_invoice.html
Labels: fix

#8056 fix: allow attendee to checkin for multiple days
  app/api/attendees.py
  app/api/schema/attendees.py
Labels: fix

#8132 feat: Group: add followers count
  app/api/schema/groups.py
  app/models/group.py
  migrations/versions/rev-2021-07-29-23:55:46-f52267133dcc_.py
Labels: feature
