Repository fossasia/open-event-server, pull requests merged in 2021-12, with the labels that each got.

#8431 fix: Removing payment method types in stripe
  app/api/helpers/payment.py
Labels: fix

#8433 fix: Add log level for flask_cors
  app/instance.py
Labels: fix

#8434 fix: make subjects of mails translatable
  app/api/helpers/system_mails.py
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/hr/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/te/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: fix

#8441 fix: celery job failing
  app/templates/email/monthly_payment_post_due_email.html
Labels: fix

#8450 fix: remove html tags from ical description
  app/api/helpers/calendar/ical.py
  app/api/helpers/utilities.py
Labels: fix

#8428 feat: Added payment intent for stripe
  app/api/custom/orders.py
  app/api/data_layers/ChargesLayer.py
  app/api/helpers/payment.py
  app/api/helpers/ticketing.py
  app/models/order.py
  migrations/versions/rev-2021-12-09-16:49:44-b0985248e3d9_.py
Labels: feature

#8447 fix: change number format & currency according to user language prefe…
  app/api/helpers/mail.py
  app/api/helpers/order.py
  app/templates/email/ticket_purchased_organizer.html
  app/templates/flask_ext/jinja/filters.py
  app/templates/pdf/attendees_pdf.html
  app/templates/pdf/order_invoice.html
  app/templates/pdf/orders.html
Labels: fix

#8461 chore: changing cryptography source to forked repo
  poetry.lock
  pyproject.toml
Labels: chore

#8463 fix: make subjects translatable with lazy loading
  app/api/helpers/system_mails.py
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/hr/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/te/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: fix

#8469 fix: docker build failing due to translation error
  app/api/helpers/system_mails.py
  app/templates/pdf/ticket_attendee.html
  app/templates/pdf/ticket_purchaser.html
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/hr/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/te/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: fix

#8472 chore: upgrade celery config to lowercase settings
  app/instance.py
Labels: chore

#8465 fix: add missing payment information
  app/api/custom/orders.py
Labels: fix

#8478 fix: change poetry download url to new script
  Dockerfile
  README.md
Labels: fix
