Repository fossasia/open-event-server, pull requests merged in 2021-01, with the labels that each got.

#7550 fix: wrong speaker count
  app/api/schema/event_statistics.py
  app/api/sessions.py
  app/api/speakers.py
  app/models/session_speaker_link.py
  migrations/versions/rev-2021-01-01-12:47:36-2d0760003a8a_.py
Labels: fix

#7560 fix: Send 404 instead of 401 for logged out video stream API access
  app/api/video_stream.py
  app/models/video_stream.py
Labels: fix

#7561 fix: Logic of ticket sales end patching check
  app/api/schema/tickets.py
  app/api/tickets.py
  tests/all/integration/api/ticket/__init__.py
  tests/all/integration/api/ticket/test_ticket_update.py
Labels: fix

#7545 fix: handle maxQty negative in discount code
  app/api/helpers/ticketing.py
  app/api/schema/discount_codes.py
  docs/api/blueprint/discount_codes.apib
Labels: fix

#7564 chore: Make all heroku commands parallel
  scripts/heroku.sh
Labels: chore

#7562 feat: add delete users_events_roles endpoint
  app/api/routes.py
  app/api/schema/users_events_roles.py
  app/api/users_events_roles.py
  docs/api/api_blueprint_source.apib
  docs/api/blueprint/role/users_events_roles.apib
  tests/factories/users_events_roles.py
  tests/hook_main.py
Labels: feature

#7569 fix: admin page not showing last-accessed for users in local time
  app/api/helpers/permissions.py
  app/models/user.py
Labels: fix

#7571 chore: Remove attendee Role from system
  app/api/events.py
  app/api/helpers/import_helpers.py
  app/api/schema/users.py
  app/models/event.py
  app/models/role.py
  app/models/user.py
  docs/api/blueprint/user/users.apib
  migrations/versions/rev-2021-01-05-20:43:13-4e61d4df3516_.py
  populate_db.py
  tests/factories/role.py
  tests/hook_main.py
Labels: chore

#7566 feat: remove order.user relation when not purchaser
  app/api/routes.py
  app/api/schema/orders.py
  app/models/order.py
  docs/api/blueprint/order/orders.apib
  tests/all/integration/api/helpers/order/test_edit_order.py
Labels: feature

#7573 fix: ticket quantity should be greater than 0
  app/api/schema/tickets.py
Labels: fix

#7574 chore: Move migrations to heroku release step
  Procfile
  kubernetes/run.sh
  manage.py
  scripts/container_start.sh
  scripts/heroku.sh
Labels: chore

#7575 chore: Make every heroku command parallel
  scripts/heroku.sh
Labels: chore

#7570 feat: Add UER relationship to event schema
  app/api/routes.py
  app/api/schema/events.py
  tests/all/integration/api/event/test_event_view_access.py
Labels: feature

#7576 feat: Speakers: rank column added
  app/api/schema/speakers.py
  app/models/speaker.py
  migrations/versions/rev-2021-01-07-05:19:49-3b29ea38f0cb_.py
Labels: feature

#7579 chore: Check multiple heads in CI
  .circleci/config.yml
  migrations/versions/rev-2021-01-07-05:19:49-3b29ea38f0cb_.py
  scripts/test_multiple_heads.sh
Labels: chore

#7582 fix: Ticket id -> name when ticket sold out
  app/models/ticket.py
Labels: fix

#7583 feat: Add stream exists API
  app/api/events.py
  app/instance.py
  app/models/event.py
  tests/all/integration/api/event/test_event_misc.py
Labels: feature

#7585 chore: Register all models in shell
  app/extensions/shell.py
Labels: chore

#7584 fix: Speakers: Rename column rank-> order
  app/api/schema/speakers.py
  app/models/speaker.py
  migrations/versions/rev-2021-01-08-15:32:58-fb8dd6aed9a9_.py
Labels: fix

#7586 feat: Add access check to has-streams API
  app/api/events.py
  tests/all/integration/api/event/test_event_misc.py
Labels: feature

#7589 fix: adding demoted, migration, API change for upcoming event
  app/api/events.py
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2021-01-09-18:31:24-cd8488c19b16_.py
Labels: fix

#7580 fix: enhance order invoice
  app/api/helpers/order.py
  app/templates/pdf/order_invoice.html
Labels: fix

#7578 feat: create date route for events
  app/api/custom/events.py
  app/instance.py
  tests/all/integration/api/event/test_event_session_distinct_dates.py
Labels: feature

#7581 feat: Add user favourite session feature
  app/api/routes.py
  app/api/schema/sessions.py
  app/api/schema/user_favourite_sessions.py
  app/api/schema/users.py
  app/api/user_favourite_sessions.py
  app/models/user.py
  app/models/user_favourite_session.py
  docs/api/blueprint/session/favourite_sessions.apib
  migrations/versions/rev-2021-01-07-22:56:23-d228ae06060b_.py
  tests/factories/user_favourite_sessions.py
  tests/hook_main.py
Labels: feature

#7590 fix: Identifier based has-streams API
  app/api/events.py
  tests/all/integration/api/event/test_event_misc.py
Labels: fix

#7591 chore: Move check migration call from startup
  app/instance.py
  app/views/healthcheck.py
Labels: chore

#7592 fix: Identifier fix for has-streams, yet again
  app/api/events.py
  tests/all/integration/api/event/test_event_misc.py
Labels: fix

#7594 feat: Support including multiple relationships from same resource
  requirements/common.txt
  tests/all/integration/api/event/test_event_view_access.py
Labels: feature

#7595 fix: limit time of event duration to maximum 20 days
  app/api/events.py
Labels: fix

#7593 feat: Availability Route added for event tickets
  app/api/tickets.py
  app/instance.py
Labels: feature

#7597 feat: add group of events feature
  app/api/groups.py
  app/api/routes.py
  app/api/schema/groups.py
  app/models/event.py
  app/models/group.py
  migrations/versions/rev-2021-01-13-12:50:33-8277175ec726_.py
Labels: feature

#7596 fix: Implement Mark Accounts as Spam
  app/api/auth.py
  app/api/schema/users.py
  app/models/user.py
  migrations/versions/rev-2021-01-13-13:56:45-a3fb59fea6c2_.py
Labels: fix

#7603 chore: Fix migration heads
  migrations/versions/rev-2021-01-13-13:56:45-a3fb59fea6c2_.py
Labels: chore

#7606 chore: Add g++ for greenlet in Dockerfile
  Dockerfile
  requirements/common.txt
Labels: chore

#7608 chore: Sync migrations
  app/models/user.py
  migrations/versions/rev-2020-10-13-17:03:26-d512ae8422a0_.py
  migrations/versions/rev-2021-01-15-23:24:18-99361377c6b6_.py
Labels: chore

#7607 feat: accept video recording field added
  app/api/schema/attendees.py
  app/models/custom_form.py
  app/models/ticket_holder.py
  migrations/versions/rev-2021-01-15-22:29:59-6314551fe3a7_.py
Labels: feature

#7609 chore: Set correct migration head
  migrations/versions/rev-2021-01-15-22:29:59-6314551fe3a7_.py
Labels: chore

#7610 feat: Add event rescheduling script
  migrations/versions/rev-2021-01-15-23:24:18-99361377c6b6_.py
  scripts/reschedule.py
Labels: feature

#7611 feat: Add after_order_message field in event
  app/api/schema/events.py
  app/models/event.py
  app/templates/email/ticket_purchased.html
  app/templates/email/ticket_purchased_attendee.html
  app/templates/pdf/order_invoice.html
  app/templates/pdf/ticket_attendee.html
  app/templates/pdf/ticket_purchaser.html
  migrations/versions/rev-2021-01-16-00:39:16-090edbf94df2_.py
Labels: feature

#7613 chore: Update translations
  app/translations/bn/LC_MESSAGES/messages.po
  app/translations/de/LC_MESSAGES/messages.po
  app/translations/es/LC_MESSAGES/messages.po
  app/translations/fr/LC_MESSAGES/messages.po
  app/translations/hi/LC_MESSAGES/messages.po
  app/translations/id/LC_MESSAGES/messages.po
  app/translations/ja/LC_MESSAGES/messages.po
  app/translations/ko/LC_MESSAGES/messages.po
  app/translations/messages.pot
  app/translations/nb_NO/LC_MESSAGES/messages.po
  app/translations/pl/LC_MESSAGES/messages.po
  app/translations/ru/LC_MESSAGES/messages.po
  app/translations/th/LC_MESSAGES/messages.po
  app/translations/vi/LC_MESSAGES/messages.po
  app/translations/zh_Hans/LC_MESSAGES/messages.po
  app/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: chore

#7542 chore: Use Poetry to manage Python dependencies
  .circleci/config.yml
  Dockerfile
  README.md
  app.json
  docs/installation/basic.md
  docs/installation/local.md
  docs/installation/mac-os.md
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements/dev.txt
  requirements/prod.txt
  requirements/tests.txt
Labels: chore

#7604 feat: add relation endpoints in group
  app/api/events.py
  app/api/groups.py
  app/api/routes.py
  app/api/schema/events.py
  app/api/schema/groups.py
  app/api/schema/users.py
  app/api/users.py
Labels: feature

#7618 feat: Attendee Form: Add Instagram and Linkedin
  app/api/schema/attendees.py
  app/models/custom_form.py
  app/models/ticket_holder.py
  migrations/versions/rev-2021-01-18-00:12:27-9afc35c9f00f_.py
Labels: feature

#7639 fix: UER permissions and remove redundant fetch_as
  app/api/access_codes.py
  app/api/custom_forms.py
  app/api/event_copyright.py
  app/api/faq_types.py
  app/api/faqs.py
  app/api/feedbacks.py
  app/api/helpers/permission_manager.py
  app/api/microlocations.py
  app/api/order_statistics/tickets.py
  app/api/role_invites.py
  app/api/session_types.py
  app/api/social_links.py
  app/api/speakers.py
  app/api/speakers_calls.py
  app/api/sponsors.py
  app/api/tax.py
  app/api/ticket_tags.py
  app/api/tickets.py
  app/api/tracks.py
  app/api/user_emails.py
  app/api/users_events_roles.py
  docs/general/permissions.md
  tests/all/integration/api/event/test_event_roles.py
Labels: fix

#7641 fix: Datetime in order emails
  app/templates/email/ticket_purchased.html
  app/templates/email/ticket_purchased_attendee.html
  app/templates/flask_ext/jinja/filters.py
  app/templates/pdf/sessions_pdf.html
Labels: fix

#7617 feat: remove owner role deletion
  app/api/users_events_roles.py
Labels: feature

#7643 fix: group relation to user
  app/api/schema/users.py
Labels: fix

#7644 feat: Add contact-organizer end-point.
  app/api/custom/events.py
  app/api/helpers/mail.py
  app/api/helpers/tasks.py
  app/models/mail.py
  app/templates/email/organizer_contact_attendee.html
Labels: feature

#7645 fix: Attendee Form: Update field names
  app/models/custom_form.py
  migrations/versions/rev-2021-01-21-01:28:36-102aec60f690_.py
Labels: fix

#7650 fix: All permission and logical issues with roles and invites
  app/api/events.py
  app/api/role_invites.py
  app/api/users_events_roles.py
  app/models/event.py
  app/models/role_invite.py
  app/models/user.py
  tests/all/integration/api/event/test_event_roles.py
  tests/factories/role_invite.py
Labels: fix

#7651 chore: Attendee form consent field name update
  app/models/custom_form.py
  migrations/versions/rev-2021-01-21-21:02:25-6874747d4c65_.py
Labels: chore

#7655 fix: Show whitespace in after order message
  app/templates/email/ticket_purchased.html
  app/templates/email/ticket_purchased_attendee.html
  app/templates/flask_ext/jinja/filters.py
  app/templates/pdf/order_invoice.html
  app/templates/pdf/ticket_attendee.html
  app/templates/pdf/ticket_purchaser.html
Labels: fix

#7658 fix: Cache and optimize event statistics
  app/api/roles.py
  app/api/schema/event_statistics.py
  app/api/schema/users_events_roles.py
  app/models/users_events_role.py
  tests/all/integration/api/helpers/test_permission_manager.py
Labels: fix

#7659 fix: role deletion bug
  app/api/roles.py
  tests/hook_main.py
Labels: fix

#7652 feat: add coorganizer check for creating group
  app/api/groups.py
  app/api/schema/groups.py
  app/models/event.py
  tests/all/integration/api/group/test_group_misc.py
  tests/factories/group.py
Labels: feature

#7662 fix: Add line break in contact organizer message
  app/api/custom/events.py
  app/templates/email/organizer_contact_attendee.html
Labels: fix

#7666 fix: Make event, user, role non nullable
  migrations/versions/rev-2021-01-24-07:16:50-edd5cb637adc_.py
Labels: fix

#7667 fix: Allow user to cancel orders
  app/api/orders.py
  app/models/order.py
Labels: fix

#7663 fix: Custom Forms: add column position
  app/api/schema/custom_forms.py
  app/models/custom_form.py
  migrations/versions/rev-2021-01-26-00:36:07-3344045f07d3_.py
Labels: fix

#7673 feat: Add exhibitor API
  app/api/exhibitors.py
  app/api/routes.py
  app/api/schema/events.py
  app/api/schema/exhibitors.py
  app/models/event.py
  app/models/exhibitor.py
  app/models/helpers/timestamp.py
  app/models/video_channel.py
  docs/api/api_blueprint_source.apib
  docs/api/blueprint/exhibitors.apib
  migrations/versions/rev-2021-01-26-00:36:07-3344045f07d3_.py
  migrations/versions/rev-2021-01-27-06:35:31-51f48128d87f_add_exhibitor.py
  tests/factories/exhibitor.py
  tests/hook_main.py
Labels: feature

#7678 chore: Deploy docs using CircleCI
  .circleci/config.yml
  scripts/push_api_docs.sh
Labels: chore

#7679 fix: Make event identifier unique
  app/models/event.py
  migrations/versions/rev-2021-01-28-10:02:24-f90a6185c469_event_identifier_unique.py
Labels: fix

#7682 fix: allow deletion of user when it's order are being past
  app/api/users.py
Labels: fix

#7681 feat: Add ICS attachment to order emails
  app/api/helpers/files.py
  app/api/helpers/mail.py
  app/api/helpers/tasks.py
Labels: feature

#7683 fix: Check mail bcc to avoid KeyError
  app/api/helpers/mail.py
Labels: fix

#7675 fix: ticket cancellation mail message change
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
Labels: fix

#7687 fix: Correct link to CfS session view page instead of public session page
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/api/sessions.py
  app/models/session.py
Labels: fix

#7688 fix: Add speaker.address column
  app/api/schema/speakers.py
  app/models/speaker.py
  migrations/versions/rev-2021-01-31-01:41:31-0c584e84a77b_add_speaker_address.py
Labels: fix

#7648 feat: Added soft closing date column for CFS
  app/api/schema/speakers_calls.py
  app/models/speakers_call.py
  migrations/versions/rev-2021-01-21-04:27:42-fbca765f3c76_.py
Labels: feature

#7680 fix: making access code and discount code valid till event sales ends
  app/api/discount_codes.py
  app/api/helpers/ticketing.py
  app/api/schema/access_codes.py
  app/api/schema/discount_codes.py
  app/models/access_code.py
  app/models/discount_code.py
Labels: fix
