Repository fossasia/open-event-server, pull requests merged in 2021-09, with the labels that each got.

#8197 fix: change 'Test Slide' to 'Slides'
  app/models/custom_form.py
Labels: fix

#8198 fix: convert zip code from int to string for leading zero
  app/api/schema/tax.py
  app/models/tax.py
  migrations/versions/rev-2021-09-04-21:16:18-09c177e36ac2_.py
Labels: fix

#8159 chore: add API docs for video-streams endpoint
  docs/api/api_blueprint_source.apib
  docs/api/blueprint/video_stream.apib
Labels: chore

#8202 fix: add app logo and invoice number in invoice header
  app/api/helpers/order.py
  app/templates/pdf/order_invoice.html
Labels: fix

#8204 chore: enhance organizer mail on order
  app/api/helpers/mail.py
  app/api/helpers/system_mails.py
  app/templates/email/ticket_purchased_organizer.html
Labels: chore

#8218 fix: Improve Installation documentation
  docs/installation/basic.md
Labels: docs, fix

#8223 fix: type errors due to pytype upgrade
  app/api/chat/rocket_chat.py
  app/api/helpers/mail.py
  app/api/sessions.py
  app/api/video_channels/bbb.py
  poetry.lock
  pyproject.toml
Labels: fix

#8213 chore: fix order invoice format
  app/api/helpers/order.py
  app/templates/pdf/order_invoice.html
Labels: chore

#8184 feat: resend invite api for group role
  app/api/custom/group_role_invite.py
  app/instance.py
Labels: feature

#8237 fix: open session link directly
  app/api/sessions.py
Labels: fix

#8241 fix: Ticket and Organizer Email should not have a Horizontal Line
  app/templates/email/ticket_purchased.html
Labels: fix

#8224 feat: add purchase on invoice backend
  app/api/schema/events.py
  app/api/schema/orders.py
  app/models/event.py
  migrations/versions/rev-2021-09-22-22:38:58-3a14893d21f0_.py
Labels: feature, has-migration

#8242 fix: change query for my-tickets
  app/api/orders.py
Labels: fix

#8243 chore: fix order invoice format
  app/api/helpers/order.py
  app/templates/pdf/order_invoice.html
Labels: chore
