Repository fossasia/open-event-server, pull requests merged in 2021-06, with the labels that each got.

#7998 fix: flask-version-downgrade to 2.7.0
  poetry.lock
  pyproject.toml
Labels: fix

#7918 fix: adding created at in group schema
  app/api/schema/groups.py
Labels: fix

#7852 fix: Set expired time of refreshed access token to 90 minutes
  app/api/auth.py
Labels: fix

#7977 fix: attendee checkin checkout
  app/api/attendees.py
Labels: fix

#7978 fix: remove external gravatar usage
  app/models/user_favourite_session.py
Labels: fix

#7994 fix: enable recording of BBB video stream by default
  app/api/video_stream.py
Labels: fix

#7912 fix: allow user to see events of group, he is an organizer
  app/api/events.py
Labels: fix

#7915 fix: Session: add options for level field
  app/api/helpers/static.py
  app/api/schema/sessions.py
  docs/api/blueprint/session/sessions.apib
  migrations/versions/rev-2021-05-10-23:16:58-f19f66ce1476_.py
  tests/all/integration/api/session/test_session_forms_api.py
Labels: fix

#8013 feat: Session Export Show Average Rating and Number of Ratings
  app/api/helpers/csv_jobs_util.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/factories/common.py
Labels: feature

#7907 feat: Create our own end point for video recording using BBB API
  app/api/routes.py
  app/api/schema/video_recordings.py
  app/api/schema/video_stream.py
  app/api/video_recordings.py
  app/api/video_stream.py
  app/models/video_recording.py
  migrations/versions/rev-2021-04-23-22:23:47-a739ff6a3855_.py
Labels: feature

#8021 fix: allow attendee checkin for several days
  app/api/attendees.py
Labels: LGTM, fix

#7975 feat: Speaker/Session CSV/PDF Export should adhere to filters
  app/api/exports.py
  app/api/helpers/tasks.py
  docs/api/blueprint/event/event_export.apib
Labels: LGTM, feature

#8025 fix: Loading all events which are owned and organised by user, on dashboard
  app/api/events.py
Labels: fix

#8027 fix: Load notification if target of notification is null
  app/api/schema/notifications.py
Labels: LGTM, fix

#8020 chore: addding unit test for missing validation
  tests/all/unit/api/validation/test_events.py
  tests/all/unit/api/validation/test_sessions_types.py
  tests/all/unit/api/validation/test_tracks.py
Labels: chore

#8017 chore: adding unit test for unfinished validations
  tests/all/unit/api/validation/test_discount_codes.py
  tests/all/unit/api/validation/test_sessions.py
  tests/all/unit/api/validation/test_tickets.py
Labels: chore

#8024 chore: test all exceptions
  tests/all/unit/api/helpers/test_exceptions.py
Labels: chore

#8031 feat: Add start page event column in settings table
  app/api/schema/settings.py
  app/models/setting.py
  docs/api/blueprint/settings.apib
  migrations/versions/rev-2021-06-11-22:24:30-ef7e7e7b9d1b_.py
Labels: feature, has-migration

#8019 fix: add missing fields in ticket csv
  app/api/helpers/csv_jobs_util.py
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/factories/order.py
Labels: LGTM, fix

#8041 chore: Clean out-of-tree code
  README.md
  autodeploy/auto_updater.py
  autodeploy/docker.py
  autodeploy/git.py
  autodeploy/main.py
  manage.py
Labels: chore

#7914 feat: groups follow api
  app/api/groups.py
  app/api/routes.py
  app/api/schema/groups.py
  app/api/schema/user_follow_groups.py
  app/api/schema/users.py
  app/api/user_follow_groups.py
  app/api/users.py
  app/models/group.py
  app/models/user_follow_group.py
  migrations/versions/rev-2021-05-06-16:11:27-4a453095d93e_.py
Labels: feature, has-migration

#8030 chore: logging for auth
  app/api/auth.py
  app/api/users.py
Labels: chore

#8015 feat: Add Multiple Event "Documents" to the system
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2021-06-20-13:53:52-ff6a976109fd_.py
Labels: feature, has-migration

#8058 fix: make humanize test timezone aware
  tests/all/integration/api/helpers/test_humanize_helper.py
Labels: fix

#8060 fix: resolve migrations issue
  migrations/versions/rev-2021-05-06-16:11:27-4a453095d93e_.py
Labels: fix

#8029 feat: Events: add video enable column
  app/api/schema/events.py
  app/models/event.py
  migrations/versions/rev-2021-06-11-00:45:55-3f0ae16c8c11_.py
Labels: feature, has-migration

#8062 feat: add check for missing name/link in event document
  app/api/events.py
Labels: feature

#8063 fix: migrating to pytest
  tests/all/integration/api/helpers/test_csv_jobs_util.py
  tests/all/integration/api/helpers/test_errors.py
  tests/all/integration/api/helpers/test_events.py
  tests/all/integration/api/helpers/test_export_helpers.py
  tests/all/integration/api/helpers/test_files.py
  tests/all/integration/api/helpers/test_jwt.py
  tests/all/integration/api/helpers/test_log.py
  tests/all/integration/api/helpers/test_order.py
  tests/all/integration/api/helpers/test_pentabarfxml.py
  tests/all/integration/api/helpers/test_permission_manager.py
  tests/all/integration/api/helpers/test_storage.py
  tests/all/integration/api/helpers/test_user.py
  tests/all/integration/api/helpers/test_xcal.py
  tests/all/integration/api/validation/test_created_at.py
  tests/all/integration/api/validation/test_discount_codes.py
  tests/all/integration/test_migrations.py
Labels: fix

#8051 fix: allow unique group followers
  app/models/user_follow_group.py
  migrations/versions/rev-2021-06-22-04:39:20-6b3498cc0457_.py
Labels: fix

#8057 feat: Create BBB recordings overview for admins and enhance admin video area
  app/api/routes.py
  app/api/video_recordings.py
Labels: feature
